id: update_references
label: Update References
source:
  plugin: update_references
  batch_size: 50
  trackBy: 'source_id'
destination:
#  Perhaps separate into node and paragraph with real ids
  plugin: entity:node
process:
  nid: source_id
migration_dependencies:
  required:
    - service_details
