id: update_redirects
label: Update Redirects
source:
  plugin: update_redirects
  batch_size: 50
destination:
  plugin: entity:redirect
  default_bundle: redirect
process:
  rid: rid
  redirect_redirect: uri
migration_dependencies:
  required:
    - service_details
