id: update_references_paragraph
label: Update References Paragraph
source:
  plugin: update_references_paragraph
  batch_size: 50
  trackBy: 'source_id'
destination:
  plugin: entity:paragraph
process:
  id: source_id
migration_dependencies:
  required:
    - service_details
