<?php

/**
 * @file
 * ISW Module file creates image styles on image upload and via queue.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\file\Entity\File;

/**
 * Implements hook_ENTITY_insert() for crop entity.
 */
function image_style_regenerate_crop_insert(EntityInterface $entity) {
  if ($entity->get('entity_type')->value == 'file') {
    if ($file = File::load($entity->get('entity_id')->value)) {
      \Drupal::service('image_style_regenerate.warmer')->warmUp($file);
    }
  }
}

/**
 * Implements hook_ENTITY_update() for crop entity.
 */
function image_style_regenerate_crop_update(EntityInterface $entity) {
  if ($entity->get('entity_type')->value == 'file') {
    if ($file = File::load($entity->get('entity_id')->value)) {
      \Drupal::service('image_style_regenerate.warmer')->warmUp($file);
    }
  }
}
