mass_utility.sendgrid:
  type: config_object
  label: 'Mass.gov SendGrid settings'
  mapping:
    template_id:
      type: string
      label: 'SendGrid dynamic template ID'
    asm_group_id:
      type: integer
      label: 'SendGrid unsubscribe group ID'
