services:
  # This is the service name used when running ddev commands accepting the
  # --service flag.
  backstop:
    # This is the name of the container. It is recommended to follow the same
    # name convention used in the main docker-compose.yml file.
    container_name: ddev-${DDEV_SITENAME}-backstop
    build:
      context: './backstopBuild'
      args:
        BASE_IMAGE: backstopjs/backstopjs:6.3.25
        username: $DDEV_USER
        uid: $DDEV_UID
        gid: $DDEV_GID
    image: ddev-backstopjs:6.3.25-${DDEV_SITENAME}-built
    user: '$DDEV_UID:$DDEV_GID'
    # Add init to reap Chrome processes, as noted at
    # https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker
    init: true
    entrypoint: [ /entrypoint.sh ]
    volumes:
      - ../backstop:/src
      - .:/mnt/ddev_config:ro
    shm_size: 2gb
    environment:
      - DDEV_HOSTNAME
      - LOWER_ENVIR_AUTH_USER
      - LOWER_ENVIR_AUTH_PASS
      - MASS_BYPASS_RATE_LIMIT
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
