---
# Docker-ChromeDriver configuration for DDEV-Local.
# There is one item that must be configured in this file in order for it to
# work, please see below.

version: '3.6'
services:
  chromedriver:
    image: seleniarm/standalone-chromium:4.1.4-20220429
    shm_size: 2gb
    container_name: ddev-${DDEV_SITENAME}-chromedriver
    expose:
      - 7900
    ports:
      - 5900:5900
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTPS_EXPOSE=7900:7900
      - HTTP_EXPOSE=7910:7900
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    external_links:
      - ddev-router:${DDEV_SITENAME}.${DDEV_TLD}
    volumes:
      - ".:/mnt/ddev_config"

  web:
    links:
      - chromedriver
    environment:
      # *** One of these must be uncommented ***
      # In order for the system to work, one of these must be uncommented so
      # that the test system can connect to the database.
      # - SIMPLETEST_DB=sqlite://tmp/test.sqlite
      #
      # Note: Do not modify the base URL value.
      - BROWSERTEST_OUTPUT_DIRECTORY=/tmp
      - BROWSERTEST_OUTPUT_BASE_URL=${DDEV_PRIMARY_URL}
      - DTT_MINK_DRIVER_ARGS=["chrome", null, "http://chromedriver:4444"]
