---
# Selenium Chrome configuration for DDEV-Local.

version: '3.6'
services:
  selenium-chrome:
    image: seleniarm/standalone-chromium:4.1.4-20220429
    container_name: ddev-${DDEV_SITENAME}-selenium-chrome
    # todo: Enable this and remove the port below when ddev's router is fixed.
    # Remember that ddev _copies_ this file so it will need to be updated or
    # deleted to take effect.
    # https://discord.com/channels/664580571770388500/976181828341866526
    # https://github.com/drud/ddev/pull/3861
    # expose:
      # The internal noVNC port, which operates over HTTP so it can be exposed
      # through the router.
      # - 7900
    #    environment:
    #      - VIRTUAL_HOST=$DDEV_HOSTNAME
    #      - HTTPS_EXPOSE=7900:7900
    #      - HTTP_EXPOSE=7910:7900
    #    external_links:
    #      - ddev-router:${DDEV_SITENAME}.${DDEV_TLD}
    ports:
      # VNC access for a traditional VNC client like macOS "Screen Sharing".
      - "5900:5900"
      # Remove this when the router is enabled.
      - "7910:7900"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - ".:/mnt/ddev_config"

  web:
    links:
      - selenium-chrome
    environment:
      - BROWSERTEST_OUTPUT_DIRECTORY=/tmp
      # Note: Do not modify the base URL value.
      - BROWSERTEST_OUTPUT_BASE_URL=${DDEV_PRIMARY_URL}
      # Use disable-dev-shm-usage instead of setting shm_usage
      # https://developers.google.com/web/tools/puppeteer/troubleshooting#tips
      # The format of chromeOptions is defined at https://chromedriver.chromium.org/capabilities
      - 'DTT_MINK_DRIVER_ARGS=["chrome", {"chromeOptions": {"args": ["disable-dev-shm-usage"]}}, "http://selenium-chrome:4444"]'
