<?php

/**
 * Create redirects for iframe external resources.
 */
function mass_validation_update_10002() {
  // Load the necessary services
  /** @var \Drupal\redirect\RedirectRepository $redirect_repository */
  $redirect_repository = \Drupal::service('redirect.repository');
  /** @var \Drupal\path_alias\AliasManagerInterface $path_alias_manager */
  $path_alias_manager = \Drupal::service('path_alias.manager');

  // Set up an array for your redirects
  $redirects = [
    '/kb/iframe-embeding' => 'https://massgovdigital.gitbook.io/knowledge-base/authoring-and-editing/embedding-iframes-on-mass.gov',
    '/forms/iframe-request-form' => 'https://massgov.formstack.com/forms/iframe_request_form',
  ];

  $redirect_service = \Drupal::entityTypeManager()->getStorage('redirect');
  // Process each redirect
  foreach ($redirects as $source => $destination) {
    $source_path = $path_alias_manager->getPathByAlias($source);

    // Check if a redirect already exists.
    if ($redirect_repository->findMatchingRedirect($source)) {
      \Drupal::messenger()->addWarning(t('The redirect from @source to @destination already exists.', ['@source' => $source, '@destination' => $destination]));
      continue;
    }

    // Create the redirect.
    $redirect = $redirect_service->create([
      'redirect_source' => [
        'path' => trim($source_path, '/')
      ],
      'redirect_redirect' => ['uri' => $destination],
      'status_code' => 301,
    ]);
    $redirect->save();

  }
}
