_core:
  default_config_hash: u-Hwiuc7ZsrDgMBe-ZqH1arPOFj4hfylWCJ7f2qhsgQ
theme_list:
  cobalt: Cobalt
  ambiance: Ambiance
  chaos: Chaos
  chrome: Chrome
  clouds: Clouds
  clouds_midnight: 'Clouds Midnight'
  crimson_editor: 'Crimson Editor'
  dawn: Dawn
  dreamweaver: Dreamweaver
  eclipse: Eclipse
  github: Github
  idle_fingers: 'Idle Fingers'
  iplastic: Iplastic
  katzenmilch: Katzenmilch
  kr_theme: 'Kr Theme'
  kuroir: Kuroir
  merbivore: Merbivore
  merbivore_soft: 'Merbivore Soft'
  mono_industrial: 'Mono Industrial'
  monokai: Monokal
  pastel_on_dark: 'Pastel On Dark'
  solarized_dark: 'Solarized Dark'
  solarized_light: 'Solarized Light'
  sqlserver: 'Sql Server'
  terminal: Terminal
  textmate: Textmate
  tomorrow: 'Tomorrow Night'
  tomorrow_night: 'Tomorrow Night'
  tomorrow_night_blue: 'Tomorrow Night Blue'
  tomorrow_night_bright: 'Tomorrow Night Bright'
  tomorrow_night_eighties: 'Tomorrow Night Eighties'
  twilight: Twilight
  vibrant_ink: 'Vibrant Ink'
  xcode: Xcode
syntax_list:
  abap: Abap
  abc: Abc
  actionscript: 'Action Script'
  ada: Ada
  apache_conf: 'Apache Conf'
  applescript: 'Apple Script'
  asciidoc: Asciidoc
  assembly_x86: 'Assembly x86'
  autohotkey: Autohotkey
  batchfile: Batchfile
  bro: Bro
  c9search: C9search
  c_cpp: C/C++
  cirru: Cirru
  clojure: Clojure
  cobol: Cobol
  coffee: Coffee
  coldfusion: Coldfusion
  csharp: 'C#'
  css: CSS
  curly: Curly
  d: D
  dart: Dart
  diff: Diff
  django: Django
  dockerfile: DOckerfile
  dot: Dot
  drools: Drools
  eiffel: Eiffel
  ejs: Ejs
  elixir: Elixir
  elm: Elm
  erlang: Erlang
  forth: Forth
  fortran: Fortran
  ftl: Ftl
  gcode: Gcode
  gherkin: Gherkin
  gitignore: Gitignore
  glsl: Glsl
  gobstones: Gobstones
  golang: Golang
  groovy: Groovy
  haml: Haml
  handlebars: Handlebars
  haskell: Haskell
  haskell_cabal: 'Haskel Cabal'
  haxe: Haxe
  hjson: HJSON
  html: HTML
  html_elixir: 'Html Elixir'
  html_ruby: 'Html Ruby'
  ini: Ini
  io: Io
  jack: Jack
  jade: Jade
  java: Java
  javascript: Javascript
  json: JSON
  jsoniq: Jsoniq
  jsp: Jsp
  jsx: Jsx
  julia: Julia
  kotlin: Kotlin
  latex: Latex
  lean: Lean
  less: LESS
  liquid: Liquid
  lisp: Lisp
  live_script: 'Live Script'
  livescript: Livescript
  logiql: Logiql
  lsl: Lsl
  lua: Lua
  luapage: Luapage
  lucene: Lucene
  makefile: Makefile
  markdown: Markdown
  mask: Mask
  matlab: Matlab
  maze: Maze
  mel: Mel
  mips_assembler: 'Mips Assembler'
  mipsassembler: 'Mips Assembler'
  mushcode: Mushcode
  mysql: Mysql
  nix: Nix
  nsis: Nsis
  objectivec: 'Objective C'
  ocaml: Ocaml
  pascal: Pascal
  perl: Perl
  pgsql: Pgsql
  php: PHP
  plain_text: 'Plain Text'
  powershell: 'Power Shell'
  praat: Praat
  prolog: Prolog
  properties: Properties
  protobuf: Protobuf
  python: Python
  r: R
  razor: Razor
  rdoc: Rdoc
  rhtml: RHtml
  rst: Rst
  ruby: Ruby
  rust: Rust
  sass: Sass
  scad: Scad
  scala: Scala
  scheme: Scheme
  scss: SCSS
  sh: Sh
  sjs: Sjs
  smarty: Smarty
  snippets: Snippets
  soy_template: 'Soy Template'
  space: Space
  sql: Sql
  sqlserver: Sqlserver
  stylus: Stylus
  svg: svg
  swift: Swift
  swig: swig
  tcl: Tcl
  tex: Tex
  text: Text
  textile: Textile
  toml: Toml
  tsx: Tsx
  twig: Twig
  typescript: Typescript
  vala: Vala
  vbscript: Vbscript
  velocity: Velocity
  verilog: Verilog
  vhdl: Vhdl
  wollok: Wollok
  xml: XML
  xquery: Xquery
  yaml: YAML
theme: cobalt
syntax: html
height: 300px
width: 100%
font_size: 12pt
line_numbers: true
show_invisibles: false
print_margins: true
auto_complete: true
use_wrap_mode: true
