profile: bedrock
moderation: false
on_demand: false
chat_manual_models: 'us.anthropic.claude-sonnet-4-20250514-v1:0'
embeddings_manual_models: 'us.anthropic.claude-sonnet-4-20250514-v1:0'
text_to_image_manual_models: ''
_core:
  default_config_hash: Pzf4mDgik_4Ep57PbVioe7wYpswcYB2TIEuB3sCXj4U
