profile: bedrock
moderation: false
on_demand: true
chat_manual_models: 'anthropic.claude-3-sonnet-20240229-v1:0'
embeddings_manual_models: 'anthropic.claude-3-sonnet-20240229-v1:0'
text_to_image_manual_models: ''
_core:
  default_config_hash: Pzf4mDgik_4Ep57PbVioe7wYpswcYB2TIEuB3sCXj4U
