status: 1
pattern: '[term:field_billing_customer_name] ([term:field_billing_customer_group]-[term:field_billing_customer_code])'
escape: false
dependencies:
  config:
    - taxonomy.vocabulary.billing_organizations
php: false
