status: 1
pattern: '[term:field_billing_customer_name] ([term:field_billing_customer_group]-[term:field_billing_customer_code])'
php: false
escape: false
dependencies:
  config:
    - taxonomy.vocabulary.billing_organizations
escape: false
preserve_titles: false
save: 0
chunk: '50'
new_entity_action: '1'
