_core:
  default_config_hash: cOqVnz_7pbb_0R31nQwih4Gh8XkmIbyFagFp6uUPaOc
coffee_menus:
  admin: admin
  mass-dashboard: mass-dashboard
  footer: footer
  footer-new: footer-new
  footer-1: footer-1
  footer-2: footer-2
  footer-3: footer-3
  main: main
  social: social
  tools: tools
  account: account
  utility: utility
max_results: 7
