log_ignored_config: {  }
log_destination:
  custom: custom
  default: '0'
  mail: '0'
_core:
  default_config_hash: XmAs9nbCHoc6DoEAUPbXoiDvo91WF8JHqbJQfd1sHB4
log_email_address: ''
ignore_config_import: true
