module:
  access_unpublished: 0
  acquia_connector: 0
  acquia_purge: 0
  actions_permissions: 0
  address: 0
  admin_toolbar: 0
  allowed_formats: 0
  auto_entitylabel: 0
  autologout: 0
  block: 0
  breakpoint: 0
  cache_metrics: 0
  ckeditor: 0
  clamav: 0
  cloudflare: 0
  components: 0
  conditional_fields: 0
  config: 0
  config_log: 0
  contact: 0
  content_moderation: 0
  crop: 0
  csv_serialization: 0
  ctools: 0
  datalayer: 0
  datetime: 0
  datetime_range: 0
  diff: 0
  draggableviews: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_entity_reference: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  encrypt: 0
  entity: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_tokens: 0
  field_ui: 0
  file: 0
  file_browser: 0
  file_entity_delete: 0
  file_upload_submit: 0
  filter: 0
  flag: 0
  flood_unblock: 0
  focal_point: 0
  ga_login: 0
  geocoder: 0
  geocoder_address: 0
  geocoder_field: 0
  geocoder_geofield: 0
  geofield: 0
  google_map_field: 0
  google_tag: 0
  handy_cache_tags: 0
  help: 0
  http_response_headers: 0
  image: 0
  imagick: 0
  inline_entity_form: 0
  inline_form_errors: 0
  jsonapi: 0
  jsonapi_page_limit: 0
  key: 0
  key_value_field: 0
  libraries: 0
  link: 0
  linkit: 0
  mailsystem: 0
  mandrill: 0
  mass_admin_pages: 0
  mass_admin_toolbar: 0
  mass_alerts: 0
  mass_caching: 0
  mass_content: 0
  mass_content_api: 0
  mass_content_moderation: 0
  mass_decision_tree: 0
  mass_docs: 0
  mass_entityaccess_userreference: 0
  mass_entityreference: 0
  mass_feedback_form: 0
  mass_feedback_loop: 0
  mass_fields: 0
  mass_flagging: 0
  mass_formatters: 0
  mass_hardening: 0
  mass_jsonapi: 0
  mass_map: 0
  mass_media: 0
  mass_metatag: 0
  mass_migration: 0
  mass_more_lists: 0
  mass_nav: 0
  mass_schema_apply_action: 0
  mass_schema_collection_page: 0
  mass_schema_event: 0
  mass_schema_government_service: 0
  mass_schema_metatag: 0
  mass_schema_news_article: 0
  mass_schema_place: 0
  mass_schema_unit_price_specification: 0
  mass_schema_web_page: 0
  mass_search: 0
  mass_search_suppression: 0
  mass_serializer: 0
  mass_site_map: 0
  mass_styles: 0
  mass_superset: 0
  mass_tours: 0
  mass_types: 0
  mass_validation: 0
  mass_views: 0
  mass_workbench_ui: 0
  maxlength: 0
  mayflower: 0
  media: 0
  media_entity_actions: 0
  media_entity_download: 0
  memcache: 0
  menu_ui: 0
  metatag: 0
  metatag_google_cse: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_views: 0
  migrate: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_tools: 0
  monolog: 0
  node: 0
  node_edit_protection: 0
  node_title_help_text: 0
  office_hours: 0
  options: 0
  paragraphs: 0
  paragraphs_type_help: 0
  password_policy: 0
  password_policy_characters: 0
  password_policy_length: 0
  path: 0
  path_redirect_import: 0
  pathologic: 0
  pfdp: 0
  prepopulate: 0
  purge: 0
  purge_drush: 0
  purge_processor_cron: 0
  purge_processor_lateruntime: 0
  purge_queuer_coretags: 0
  purge_queues: 0
  purge_ui: 0
  quick_node_clone: 0
  rabbit_hole: 0
  real_aes: 0
  redirect: 0
  redirect_404: 0
  rest: 0
  restui: 0
  rh_node: 0
  rh_taxonomy: 0
  route_iframes: 0
  scheduler: 0
  scheduler_content_moderation_integration: 0
  scheduler_media: 0
  schema_article: 0
  schema_article_example: 0
  schema_item_list: 0
  schema_metatag: 0
  schema_organization: 0
  schema_web_page: 0
  schema_web_site: 0
  seckit: 0
  security_review: 0
  serialization: 0
  simple_sitemap: 0
  stage_file_proxy: 0
  subpathauto: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  tfa: 0
  tfa_unblock: 0
  token: 0
  toolbar: 0
  tour: 0
  trashbin: 0
  twig_field_value: 0
  twig_tweak: 0
  user: 0
  username_enumeration_prevention: 0
  video_embed_field: 0
  video_embed_media: 0
  view_mode_page: 0
  views_autocomplete_filters: 0
  views_bulk_operations: 0
  views_custom_cache_tag: 0
  views_data_export: 0
  views_ui: 0
  workflows: 0
  mass_utility: 1
  menu_link_content: 1
  pathauto: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  mass_theme: 0
  seven: 0
  mass_admin_theme: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
profile: standard
