_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
module:
  access_unpublished: 0
  acquia_purge: 0
  actions_permissions: 0
  address: 0
  admin_toolbar: 0
  akamai: 0
  allowed_formats: 0
  asset_cache_bust: 0
  auto_entitylabel: 0
  autologout: 0
  better_exposed_filters: 0
  block: 0
  breakpoint: 0
  cache_metrics: 0
  ckeditor: 0
  ckeditor_liststyle: 0
  color: 0
  components: 0
  conditional_fields: 0
  config: 0
  config_ignore: 0
  contact: 0
  content_moderation: 0
  crop: 0
  csv_field: 0
  csv_serialization: 0
  ctools: 0
  datalayer: 0
  datatables_cdn: 0
  datetime: 0
  datetime_range: 0
  dbal: 0
  diff: 0
  draggableviews: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_entity_reference: 0
  dynamic_page_cache: 0
  editor: 0
  editoria11y: 0
  embed: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_diff_ui: 0
  entity_embed: 0
  entity_hierarchy: 0
  entity_hierarchy_breadcrumb: 0
  entity_reference_revisions: 0
  entity_reference_tree: 0
  entity_usage: 0
  entity_usage_queue_tracking: 0
  entityreference_filter: 0
  environment_indicator: 0
  field: 0
  field_group: 0
  field_tokens: 0
  field_ui: 0
  file: 0
  file_browser: 0
  file_entity_delete: 0
  file_upload_submit: 0
  filter: 0
  flag: 0
  focal_point: 0
  geocoder: 0
  geocoder_address: 0
  geocoder_field: 0
  geocoder_geofield: 0
  geofield: 0
  google_map_field: 0
  google_tag: 0
  help: 0
  http_response_headers: 0
  hux: 0
  iframe_resizer: 0
  image: 0
  imagick: 0
  inline_entity_form: 0
  inline_form_errors: 0
  jquery_ui: 0
  jquery_ui_autocomplete: 0
  jquery_ui_datepicker: 0
  jquery_ui_menu: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  jsonapi: 0
  key: 0
  key_auth: 0
  key_value_field: 0
  language: 0
  link: 0
  linkit: 0
  mailchimp_transactional: 0
  mailchimp_transactional_template: 0
  mailsystem: 0
  mass_active_directory: 0
  mass_admin_pages: 0
  mass_admin_toolbar: 0
  mass_alerts: 0
  mass_analytics: 0
  mass_auto_parents: 0
  mass_bigquery: 0
  mass_caching: 0
  mass_content: 0
  mass_content_api: 0
  mass_content_moderation: 0
  mass_decision_tree: 0
  mass_docs: 0
  mass_entity_usage: 0
  mass_entityaccess_userreference: 0
  mass_entityreference: 0
  mass_feedback_form: 0
  mass_feedback_loop: 0
  mass_fields: 0
  mass_flagging: 0
  mass_formatters: 0
  mass_hardening: 0
  mass_hierarchy: 0
  mass_jsonapi: 0
  mass_map: 0
  mass_media: 0
  mass_metatag: 0
  mass_more_lists: 0
  mass_nav: 0
  mass_redirects: 0
  mass_scheduled_transitions: 0
  mass_schema_apply_action: 0
  mass_schema_collection_page: 0
  mass_schema_event: 0
  mass_schema_government_service: 0
  mass_schema_metatag: 0
  mass_schema_news_article: 0
  mass_schema_place: 0
  mass_schema_special_announcement: 0
  mass_schema_unit_price_specification: 0
  mass_schema_web_page: 0
  mass_search: 0
  mass_search_suppression: 0
  mass_serializer: 0
  mass_site_map: 0
  mass_styles: 0
  mass_superset: 0
  mass_tours: 0
  mass_translations: 0
  mass_types: 0
  mass_unpublish_reminders: 0
  mass_validation: 0
  mass_views: 0
  mass_workbench_ui: 0
  maxlength: 0
  mayflower: 0
  media: 0
  media_diff_ui: 0
  media_entity_download: 0
  memcache: 0
  menu_ui: 0
  metatag: 0
  metatag_favicons: 0
  metatag_google_cse: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_views: 0
  migrate: 0
  monolog: 0
  mysql: 0
  node: 0
  node_edit_protection: 0
  node_title_help_text: 0
  office_hours: 0
  openid_connect: 0
  openid_connect_windows_aad: 0
  options: 0
  papaparse: 0
  paragraphs: 0
  path: 0
  path_alias: 0
  pathologic: 0
  pfdp: 0
  phpass: 0
  prepopulate: 0
  prod_no_redirect: 0
  purge: 0
  purge_drush: 0
  purge_processor_cron: 0
  purge_queuer_coretags: 0
  purge_queues: 0
  purge_ui: 0
  queue_unique: 0
  quick_node_clone: 0
  r4032login: 0
  rabbit_hole: 0
  redirect: 0
  redirect_404: 0
  require_on_publish: 0
  responsive_image: 0
  rest: 0
  rh_node: 0
  rh_taxonomy: 0
  scheduled_transitions: 0
  schema_article: 0
  schema_article_example: 0
  schema_item_list: 0
  schema_metatag: 0
  schema_organization: 0
  schema_web_page: 0
  schema_web_site: 0
  seckit: 0
  security_review: 0
  serialization: 0
  simple_sitemap: 0
  stage_file_proxy: 0
  subpathauto: 0
  system: 0
  taxonomy: 0
  telephone: 0
  term_reference_tree: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  trashbin: 0
  twig_field_value: 0
  twig_tweak: 0
  update: 0
  upgrade_status: 0
  user: 0
  username_enumeration_prevention: 0
  video_embed_field: 0
  video_embed_media: 0
  view_mode_page: 0
  views_aggregator: 0
  views_ajax_history: 0
  views_autocomplete_filters: 0
  views_bulk_edit: 0
  views_bulk_operations: 0
  views_custom_cache_tag: 0
  views_data_export: 0
  views_porter_stemmer: 0
  views_simple_math_field: 0
  views_taxonomy_term_name_into_id: 0
  views_ui: 0
  workflows: 0
  mass_utility: 1
  menu_link_content: 1
  pathauto: 1
  externalauth: 10
  views: 10
  standard: 1000
theme:
  mass_theme: 0
  seven: 0
  mass_admin_theme: 0
profile: standard
