_core:
  default_config_hash: 2h-F0MHukrrFbu21y1YR-uXZDqW44v8qmH254NAcfd4
content_root: ''
assertiveness: smart
no_load: ''
ignore_all_if_absent: ''
ignore_elements: '.ma__location-banner__image *, .ma__suggested-pages__item img, #location-listing-results img, .ma__personal-message__container .ma__image-promo__image img, .ma__key-message__inline-image img, .ma__details__content .ma__image-promos img.ma__image'
embedded_content_warning: ''
download_links: 'false'
ignore_link_strings: ''
hidden_handlers: ''
ed11y_theme: sleekTheme
shadow_components: ''
disable_sync: false
preserve_params: 'search,keys,page,language,language_content_entity'
custom_tests: 0
