_core:
  default_config_hash: 2h-F0MHukrrFbu21y1YR-uXZDqW44v8qmH254NAcfd4
content_root: ''
assertiveness: smart
no_load: ''
ignore_all_if_absent: ''
ignore_elements: '.ma__location-banner__image *, .ma__suggested-pages__item img, #location-listing-results img, .ma__personal-message__container .ma__image-promo__image img, .ma__key-message__inline-image img, .ma__details__content .ma__image-promos img.ma__image, .ma__card__img.ma__card__img--vertical img, .js-location-listing-link .ma__image-promo__image *, .user-login *'
embedded_content_warning: ''
download_links: 'false'
ignore_link_strings: ''
hidden_handlers: ''
ed11y_theme: sleekTheme
shadow_components: ''
disable_sync: false
preserve_params: 'search,keys,page,language,language_content_entity'
custom_tests: 0
panel_no_cover: ''
element_hides_overflow: ''
panel_pin: right
detect_shadow: false
watch_for_changes: 'true'
disable_live: true
live_h_inherit: ''
live_h2: ''
live_h3: ''
live_h4: ''
hide_edit_links: ''
ignore_tests:
  linkNewWindow: '0'
  linkNoText: '0'
  altEmptyLinked: '0'
  linkDocument: '0'
  linkTextIsURL: '0'
  linkTextIsGeneric: '0'
  textPossibleList: '0'
  textPossibleHeading: '0'
  textUppercase: '0'
  tableNoHeaderCells: '0'
  tableEmptyHeaderCell: '0'
  tableContainsContentHeading: '0'
  embedVideo: '0'
  embedAudio: '0'
  embedVisualization: '0'
  embedTwitter: '0'
  embedCustom: '0'
  headingEmpty: '0'
  headingIsLong: '0'
  headingLevelSkipped: '0'
  blockquoteIsShort: '0'
  altMissing: '0'
  altNull: '0'
  altMeaningless: '0'
  altURL: '0'
  altImageOf: '0'
  altDeadspace: '0'
  altLong: '0'
  altPartOfLinkWithText: '0'
