_core:
  default_config_hash: nQJetT9EarA9753WO5k31lSgoDisRG2-1uIRFODZ9tk
roles: 'administrator,admin'
assertiveness: assertive
tests_content: ''
tests_off: 'CONTRAST_WARNING_GRAPHIC,LINK_CLICK_HERE,LINK_IMAGE_ALT'
tests_dev: ''
contrast_ignore: .sr-only
contrast_check: true
dev_check_root: automatic
specify_root: .dialog-off-canvas-main-canvas
always_ignore: ''
csa_active: beta
pending_clear: ''
pending_clear_batch: 1
