_core:
  default_config_hash: 2h-F0MHukrrFbu21y1YR-uXZDqW44v8qmH254NAcfd4
content_root: ''
assertiveness: smart
no_load: ''
ignore_all_if_absent: ''
ignore_elements: ''
embedded_content_warning: ''
download_links: "a[href$='/download'], a[href$='.pdf'], a[href*='.pdf?'], a[href$='.doc'], a[href$='.docx'], a[href*='.doc?'], a[href*='.docx?'], a[href$='.ppt'], a[href$='.pptx'], a[href*='.ppt?'], a[href*='.pptx?'], a[href^='https://docs.google']"
ignore_link_strings: ''
hidden_handlers: ''
ed11y_theme: sleekTheme
shadow_components: ''
disable_sync: false
preserve_params: 'search,keys,page,language,language_content_entity'
custom_tests: 0
