content_types:
  info_details: info_details
  action: 0
  advisory: 0
  alert: 0
  binder: 0
  campaign_landing: 0
  contact_information: 0
  curated_list: 0
  decision: 0
  decision_tree: 0
  decision_tree_branch: 0
  decision_tree_conclusion: 0
  error_page: 0
  event: 0
  executive_order: 0
  external_data_resource: 0
  fee: 0
  form_page: 0
  guide_page: 0
  how_to_page: 0
  interstitial: 0
  location: 0
  location_details: 0
  news: 0
  org_page: 0
  page: 0
  person: 0
  regulation: 0
  rules: 0
  service_page: 0
  sitewide_alert: 0
  stacked_layout: 0
  topic_page: 0
  utility_drawer: 0
