_core:
  default_config_hash: 2h-F0MHukrrFbu21y1YR-uXZDqW44v8qmH254NAcfd4
content_root: ''
no_load: ''
ignore_elements: ''
embedded_content_warning: ''
assertiveness: smart
download_links: ''
ignore_link_strings: ''
hidden_handlers: ''
ignore_all_if_absent: ''
ed11y_theme: sleekTheme
shadow_components: ''
disable_sync: false
preserve_params: 'search,keys,page,language,language_content_entity'
custom_tests: 0
