content_types:
  advisory: advisory
  alert: alert
  binder: binder
  campaign_landing: campaign_landing
  contact_information: contact_information
  curated_list: curated_list
  decision: decision
  decision_tree: decision_tree
  decision_tree_branch: decision_tree_branch
  decision_tree_conclusion: decision_tree_conclusion
  event: event
  executive_order: executive_order
  external_data_resource: external_data_resource
  fee: fee
  form_page: form_page
  guide_page: guide_page
  how_to_page: how_to_page
  info_details: info_details
  location: location
  location_details: location_details
  news: news
  org_page: org_page
  person: person
  regulation: regulation
  rules: rules
  service_page: service_page
  sitewide_alert: sitewide_alert
  topic_page: topic_page
  action: 0
  error_page: 0
  interstitial: 0
  page: 0
  stacked_layout: 0
  utility_drawer: 0
