entity_types:
  entity_hierarchy_microsite: entity_hierarchy_microsite
  file: file
  media: media
  node: node
  taxonomy_term: taxonomy_term
  user: user
  access_token: 0
  ai_content_advisor_report: 0
  ai_log: 0
  contact_message: 0
  content_moderation_state: 0
  crop: 0
  entity_embed_fake_entity: 0
  eh_microsite_menu_override: 0
  flagging: 0
  user_ref_access: 0
  paragraph: 0
  path_alias: 0
  redirect: 0
  scheduled_transition: 0
  menu_link_content: 0
