_core:
  default_config_hash: 8LI-1XgwLt9hYRns_7c81S632d6JhdqXKs4vDheaG6E
description:
  type: textfield
  length: 128
icon:
  directory: core/modules/file/icons
make_unused_managed_files_temporary: false
filename_sanitization:
  transliterate: false
  replace_whitespace: false
  replace_non_alphanumeric: false
  deduplicate_separators: false
  lowercase: false
  replacement_character: '-'
