_core:
  default_config_hash: UvSCt3S_NldJPFzvhSNOy9vWoPPFhmsmTC12vtVss9s
favicon:
  mimetype: image/png
  path: libraries/mayflower-artifacts/assets/images/logo/stateseal-color.png
  use_default: false
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: false
logo:
  path: libraries/mayflower-artifacts/assets/images/logo/stateseal-color.png
  use_default: false
third_party_settings:
  shortcut:
    module_link: true
preset_accent_color: green
preset_focus_color: gin
enable_darkmode: '0'
classic_toolbar: horizontal
secondary_toolbar_frontend: false
high_contrast_mode: false
accent_color: ''
focus_color: ''
layout_density: default
show_description_toggle: false
show_user_theme_settings: true
