_core:
  default_config_hash: OhypfKr4_Eo8XwXg3Sios05lN-LjxOhSdSOSkEN9Ndo
logo:
  use_default: false
  path: libraries/mayflower-artifacts/assets/images/logo/stateseal.png
brand_image:
  use_default: false
  path: themes/custom/mass_theme/default_images/state-house-dome.jpg
