container_id: GTM-MPHNMQ
path_toggle: all_except_listed
path_list: "admin*\nbatch*\nnode/add*\nnode/*/*\nuser/*/*"
role_toggle: all_except_listed
role_list:
  - null
status_toggle: false
status_list: "403\n404"
compact_tag: true
_core:
  default_config_hash: jDM0cFYzTXKgM_I2Hbh2KcwgmmVmhymYEA9AUumduiA
