_core:
  default_config_hash: 65d5DfK5p2hQDpBskbvCIj2hSEqw_Odm2e_d46BH1Lk
default_google_tag_entity: GTM-MPHNMQ.64824a45262c46.58617083
uri: 'public:/'
compact_snippet: true
include_file: false
rebuild_snippets: true
flush_snippets: false
debug_output: false
_default_container:
  container_id: ''
  data_layer: dataLayer
  include_classes: false
  whitelist_classes: |-
    google
    nonGooglePixels
    nonGoogleScripts
    nonGoogleIframes
  blacklist_classes: |-
    customScripts
    customPixels
  include_environment: false
  environment_id: ''
  environment_token: ''
  path_toggle: 'exclude listed'
  path_list: |-
    /admin*
    /batch*
    /node/add*
    /node/*/edit
    /node/*/delete
    /user/*/edit*
    /user/*/cancel*
  role_toggle: 'exclude listed'
  role_list: {  }
  status_toggle: 'exclude listed'
  status_list: |-
    403
    404
