_core:
  default_config_hash: QfRxCsHzZ8_TOqax9jYAfQvj5Kq9Ve7vl4pVziKemhA
gtranslate_method: onfly
gtranslate_pro: 0
gtranslate_enterprise: 0
gtranslate_analytics: 0
gtranslate_look: flags_dropdown
gtranslate_flag_size: '16'
gtranslate_new_window: 1
gtranslate_main_lang: en
gtranslate_af: '1'
gtranslate_sq: '1'
gtranslate_ar: '1'
gtranslate_hy: '1'
gtranslate_az: '1'
gtranslate_eu: '1'
gtranslate_be: '1'
gtranslate_bg: '1'
gtranslate_ca: '1'
gtranslate_zh-CN: '1'
gtranslate_zh-TW: '1'
gtranslate_hr: '1'
gtranslate_cs: '1'
gtranslate_da: '1'
gtranslate_nl: '2'
gtranslate_en: '2'
gtranslate_et: '1'
gtranslate_tl: '1'
gtranslate_fi: '1'
gtranslate_fr: '2'
gtranslate_gl: '1'
gtranslate_ka: '1'
gtranslate_de: '2'
gtranslate_el: '1'
gtranslate_ht: '1'
gtranslate_iw: '1'
gtranslate_hi: '1'
gtranslate_hu: '1'
gtranslate_is: '1'
gtranslate_id: '1'
gtranslate_ga: '1'
gtranslate_it: '2'
gtranslate_ja: '1'
gtranslate_ko: '1'
gtranslate_lv: '1'
gtranslate_lt: '1'
gtranslate_mk: '1'
gtranslate_ms: '1'
gtranslate_mt: '1'
gtranslate_no: '1'
gtranslate_fa: '1'
gtranslate_pl: '1'
gtranslate_pt: '2'
gtranslate_ro: '1'
gtranslate_ru: '2'
gtranslate_sr: '1'
gtranslate_sk: '1'
gtranslate_sl: '1'
gtranslate_es: '2'
gtranslate_sw: '1'
gtranslate_sv: '1'
gtranslate_th: '1'
gtranslate_tr: '1'
gtranslate_uk: '1'
gtranslate_ur: '1'
gtranslate_vi: '1'
gtranslate_cy: '1'
gtranslate_yi: '1'
gtranslate_bn: '1'
gtranslate_bs: '1'
gtranslate_ceb: '1'
gtranslate_eo: '1'
gtranslate_gu: '1'
gtranslate_ha: '1'
gtranslate_hmn: '1'
gtranslate_ig: '1'
gtranslate_jw: '1'
gtranslate_kn: '1'
gtranslate_km: '1'
gtranslate_lo: '1'
gtranslate_la: '1'
gtranslate_mi: '1'
gtranslate_mr: '1'
gtranslate_mn: '1'
gtranslate_ne: '1'
gtranslate_pa: '1'
gtranslate_so: '1'
gtranslate_ta: '1'
gtranslate_te: '1'
gtranslate_yo: '1'
gtranslate_zu: '1'
gtranslate_my: '0'
gtranslate_ny: '0'
gtranslate_kk: '0'
gtranslate_mg: '0'
gtranslate_ml: '0'
gtranslate_si: '0'
gtranslate_st: '0'
gtranslate_su: '0'
gtranslate_tg: '0'
gtranslate_uz: '0'
gtranslate_am: '0'
gtranslate_co: '0'
gtranslate_haw: '0'
gtranslate_ku: '0'
gtranslate_ky: '0'
gtranslate_lb: '0'
gtranslate_ps: '0'
gtranslate_sm: '0'
gtranslate_gd: '0'
gtranslate_sn: '0'
gtranslate_sd: '0'
gtranslate_fy: '0'
gtranslate_xh: '0'
