_core:
  default_config_hash: N-xOd1pralXTuyyJA47dtvXWWxz3STj0hvmr0umAFmk
quality: 75
binaries: imagemagick
imagemagick_version: v6
path_to_binaries: ''
prepend: ''
log_warnings: true
debug: false
image_formats:
  PNG:
    mime_type: image/png
  JPEG:
    mime_type: image/jpeg
  JPG:
    mime_type: image/jpeg
    weight: 10
    enabled: true
  GIF:
    mime_type: image/gif
  GIF87:
    mime_type: image/gif
    weight: 10
    enabled: true
  SVG:
    mime_type: image/svg+xml
    enabled: false
  WEBP:
    mime_type: image/webp
  AVIF:
    mime_type: image/avif
    enabled: true
  TIFF:
    mime_type: image/tiff
    enabled: true
  PDF:
    mime_type: application/pdf
    enabled: true
  HEIC:
    mime_type: image/heif
    enabled: true
  BMP:
    mime_type: image/x-ms-bmp
    enabled: true
  PSD:
    mime_type: image/x-photoshop
    enabled: false
  WBMP:
    mime_type: image/vnd.wap.wbmp
    enabled: false
  XBM:
    mime_type: image/x-xbitmap
    enabled: false
  ICO:
    mime_type: image/vnd.microsoft.icon
    enabled: true
advanced:
  density: 0
  colorspace: '0'
  profile: ''
  coalesce: false
