_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: ''
    es: es
    zh-hans: zh-hans
    vi: vi
    pt-pt: pt-pt
    ht: ht
    ru: ru
    km: km
    ar: ar
    fr: fr
    cv: cv
    ko: ko
    it: it
    af: af
    lo: lo
    uk: uk
    pt-br: pt-br
    hi: hi
    ne: ne
    sq: sq
    pl: pl
    zh-hant: zh-hant
    so: so
    am: am
    '': null
    el: el
    sw: sw
    pst: pst
    prs: prs
    hmn: hmn
    tw: tw
    de: de
    he: he
    ja: ja
    nl: nl
    fa: fa
    hy: hy
    rw: rw
    my: my
  domains:
    en: ''
    es: ''
    zh-hans: ''
    vi: ''
    pt-pt: ''
    ht: ''
    ru: ''
    km: ''
    ar: ''
    fr: ''
    cv: ''
    ko: ''
    it: ''
    af: ''
    lo: ''
    uk: ''
    pt-br: ''
    hi: ''
    ne: ''
    sq: ''
    pl: ''
    zh-hant: ''
    so: ''
    am: ''
    el: ''
    sw: ''
    pst: ''
    prs: ''
    hmn: ''
    tw: ''
    de: ''
    he: ''
    ja: ''
    nl: ''
    fa: ''
    hy: ''
    rw: ''
    my: ''
selected_langcode: site_default
