_core:
  default_config_hash: 1voH1sN6U7SgNMXT8tdbT3CU2TtoqtB_xIKmn8i0VnM
mailchimp_transactional_from_name: Massgov
mailchimp_transactional_from_email: no-reply@digital.mass.gov
mailchimp_transactional_subaccount: null
mailchimp_transactional_filter_format: mailchimp
mailchimp_transactional_track_opens: false
mailchimp_transactional_track_clicks: false
mailchimp_transactional_url_strip_qs: true
mailchimp_transactional_analytics_campaign: ''
mailchimp_transactional_analytics_domains: ''
mailchimp_transactional_batch_log_queued: false
mailchimp_transactional_queue_worker_timeout: null
mailchimp_transactional_log_defaulted_sends: false
mailchimp_transactional_api_key: REDACTED
mailchimp_transactional_api_timeout: 60
mailchimp_transactional_api_classname: \Drupal\mailchimp_transactional\DrupalMailchimpTransactional
mailchimp_transactional_mail_key_blacklist: ''
mailchimp_transactional_process_async: false
