features:
  node_user_picture: 0
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
  path: themes/custom/mass_theme/images/stateseal.png
  mimetype: image/png
