start: '22:00'
end: '02:00'
max_interval: 14400
types:
  advisory: advisory
  binder: binder
  campaign_landing: campaign_landing
  curated_list: curated_list
  decision: decision
  decision_tree: decision_tree
  event: event
  executive_order: executive_order
  form_page: form_page
  guide_page: guide_page
  how_to_page: how_to_page
  info_details: info_details
  location: location
  location_details: location_details
  news: news
  org_page: org_page
  person: person
  regulation: regulation
  rules: rules
  service_page: service_page
  topic_page: topic_page
batch: '500'
_core:
  default_config_hash: KoGTqw5vvI79v-Xy-jS66FMPlCt044VAaEeVCU6h4l8
