_core:
  default_config_hash: EKYCulG-Y3pcObfUpVbl-D9T5DDX6d4hpQ-BVlSBAmw
scheme_whitelist:
  - http
  - https
  - files
  - internal
protocol_style: path
local_paths: "http://edit.mass.gov\r\nhttp://pilot.mass.gov\r\nhttp://www.mass.gov\r\nhttp://mass.gov"
