_core:
  default_config_hash: cFFLr1OzNMWsYHjKioubhwuqTLNWAGRBVqvq4DdNbkk
enabled_checks:
  - document_title_filename
  - pdf_version
  - figure_alt_text
  - tagged_pdf
  - heading_structure
  - document_title
  - heading_structure_extended
  - document_language
min_pdf_version: '1.4'
check_on_upload: true
block_failed_uploads: false
editor_instructions: 'For guidance on creating accessible PDF documents, see the <a href="/admin/config/media/pdf-accessibility/help">PDF Accessibility Help</a> page.'
