_core:
  default_config_hash: bpMUG7_m9cybmlkiNQxtOxmYmgx2eMtHSSQF2ZeT53Q
enabled_checks:
  - pdf_version
  - tagged_pdf
  - document_title
  - document_language
min_pdf_version: '1.4'
check_on_upload: true
block_failed_uploads: false
editor_instructions: 'For guidance on creating accessible PDF documents, see the <a href="https://www.mass.gov/info-details/pdf-document-accessibility-testing-checklist" target="_blank">PDF Document Accessibility Testing Checklist</a> (opens in new tab).'
