channels:
  -
    id: purgers
    grants:
      - 0
      - 2
      - 3
  -
    id: queue
    grants:
      - 0
      - 2
      - 3
  -
    id: purger_acquia_purge_fa3e594f20
    grants:
      - 0
      - 2
      - 3
  -
    id: purger_akamai_20fe5b998e
    grants:
      - 0
      - 2
      - 3
  -
    id: diagnostics
    grants:
      - 3
