channels:
  0:
    id: purgers
    grants:
      - 0
      - 2
      - 3
  1:
    id: queue
    grants:
      - 0
      - 2
      - 3
  2:
    id: diagnostics
    grants:
      - 3
  3:
    id: purger_acquia_purge_fa3e594f20
    grants:
      - 0
      - 2
      - 3
  5:
    id: purger_akamai_20fe5b998e
    grants:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
