_core:
  default_config_hash: IxLwI-D9NeuZKfY2iz87l0NeM8LfBn7IVucsc6RG6l4
auto_redirect: true
default_status_code: 301
passthrough_querystring: true
warning: false
ignore_admin_path: false
access_check: false
route_normalizer_enabled: true
canonical: true
nonclean_to_clean: true
frontpage_redirect: true
deslash: false
normalize_aliases: true
content_location_header: false
term_path_handler: true
