_core:
  default_config_hash: 33gg8hVdxE7nTswwBBOY_d2rH3XjAbBa4rw0XyMRh6Y
enabled: true
submission_interval: 24
index_now_enabled: true
index_now_preferred_engine: index_now
index_now_on_entity_save: true
