_core:
  default_config_hash: vFARRSP9-YgEArfDNYmRSg0cNFOgZPxqziffIalgLbU
max_links: 3000
cron_generate: false
cron_generate_interval: 3
generate_duration: 15000
entities_per_queue_item: 50
remove_duplicates: false
skip_untranslated: true
xsl: true
base_url: 'https://www.mass.gov'
default_variant: sitemaps
custom_links_include_images: false
disable_language_hreflang: false
excluded_languages: {  }
enabled_entity_types:
  - node
  - media
batch_process_limit: 1500
