_core:
  default_config_hash: t5W6QbLZA8s7VAoHDDldhRB2Emm1blOGOOKHMV855Gk
token: b3a1ab0c28be4e3d8e9d06f65c333205
domain_plugin_id: siteimprovedomain_single
prepublish_enabled: true
api_username: arthur@lastcallmedia.com
api_key: 6e8faa7fedff5dc35069eb894f4e52a0
enabled_content_types:
  advisory: advisory
  binder: binder
  campaign_landing: campaign_landing
  curated_list: curated_list
  decision: decision
  decision_tree: decision_tree
  event: event
  executive_order: executive_order
  form_page: form_page
  guide_page: guide_page
  how_to_page: how_to_page
  info_details: info_details
  location: location
  location_details: location_details
  news: news
  org_page: org_page
  regulation: regulation
  rules: rules
  service_details: service_details
  service_page: service_page
  topic_page: topic_page
  action: '0'
  alert: '0'
  contact_information: '0'
  decision_tree_branch: '0'
  decision_tree_conclusion: '0'
  error_page: '0'
  external_data_resource: '0'
  fee: '0'
  interstitial: '0'
  page: '0'
  person: '0'
  sitewide_alert: '0'
  stacked_layout: '0'
  utility_drawer: '0'
enabled_taxonomies:
  action_type: '0'
  adjustment_type: '0'
  advisory_publish_state: '0'
  advisory_type: '0'
  announcement_type: '0'
  billing_organizations: '0'
  binder_type: '0'
  collections: '0'
  content_type: '0'
  data_topic: '0'
  decision_participant_type: '0'
  decision_type: '0'
  document_category: '0'
  document_contacts: '0'
  document_creators: '0'
  document_other_type: '0'
  document_subjects: '0'
  document_tags: '0'
  event_type: '0'
  icons: '0'
  label: '0'
  language: '0'
  license: '0'
  location_activities: '0'
  location_icon: '0'
  location_icon_park: '0'
  rules_of_court_standing_order: '0'
  rules_of_court_type: '0'
  tags: '0'
  tx_data_resource_type: '0'
  tx_details_data_type: '0'
  tx_list_data_type: '0'
  type: '0'
  user_organization: '0'
