_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 86019609-db78-4212-aa66-94a2ae42c0c3
name: Mass.gov
mail: DigitalSupport@mass.gov
slogan: 'Official website of the Commonwealth of Massachusetts'
page:
  403: /node/3331
  404: /node/3326
  front: /node/3666
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
