_core:
  default_config_hash: c-knKQdQwnCtY9cwzSHofxLIkpZdYUGi13uCGVEFCHc
categories:
  services_info: 'Services &amp; Info'
  org_contact_info: 'Org &amp; Contact Info'
  news_events: 'News &amp; Events'
  laws_regs: 'Laws &amp; Regs'
  descision_tree: 'Decision Tree (Beta)'
fallback_label: Other
text_format: basic_html
