<?php

/**
 * @file
 * Contains schema_article.module.
 */

use Drupal\Core\Render\BubbleableMetadata;
use Drupal\mass_schema_web_page\DecisionTokenRenderer;

/**
 * Implements hook_metatag_groups_alter().
 *
 * Every module should implement this to add a flag to the object types they
 * create.
 */
function mass_schema_web_page_metatag_groups_alter(&$data) {
  $module_name = basename(__FILE__, '.module');
  foreach ($data as $key => $value) {
    if ($value['provider'] == $module_name) {
      $data[$key]['schema_metatag'] = TRUE;
    }
  }
}

/**
 * Implements hook_tokens().
 */
function mass_schema_web_page_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $replacements = [];

  if ($type === 'node' && !empty($data['node'])) {
    /** @var \Drupal\node\NodeInterface $entity */
    $entity = $data['node'];

    $renderer = new DecisionTokenRenderer(\Drupal::entityTypeManager(), \Drupal::service('file_url_generator'));
    if ($renderer->isRenderable($entity)) {
      $replacements = $renderer->getTokens($tokens, $entity);
    }
  }

  return $replacements;
}
