<?php

/**
 * @file
 * Custom code for mass_feedback_loop module.
 */

use Drupal\Core\Render\Markup;

/**
 * Implements hook_preprocess_HOOK().
 */
function mass_feedback_loop_preprocess_pager(&$variables) {
  $request = \Drupal::request();
  // Checks for main Feedback Manager page/form.
  if ($request->attributes->get('_route') == 'mass_feedback_loop.mass_feedback_loop_author_interface_form') {
    // Resets pager counter for results being reloaded via an AJAX call.
    if ($request->isXmlHttpRequest() && is_numeric($request->query->getDigits('page'))) {
      $variables['current'] = 1;
    }
    // Removes unnecessary 'First' and 'Last' navigation links from pager.
    unset(
      $variables['items']['first'],
      $variables['items']['last']
    );
  }
}

/**
 * Implements hook_theme().
 */
function mass_feedback_loop_theme() {
  return [
    'mass_survey_row' => [
      'variables' => ['data' => NULL],
    ],
  ];
}

/**
 * Implements hook_preprocess_block().
 */

function mass_feedback_loop_preprocess_block(array &$variables) {
  if ($variables['plugin_id'] === 'system_page_title_block') {
    $route_name = \Drupal::routeMatch()->getRouteName();

    if ($route_name === 'mass_feedback_loop.per_node_feedback_form') {
      $negative_feedback_url = \Drupal\Core\Url::fromRoute('view.pages_with_high_negative_feedback.page_2')->toString();
      $feedback_manager_url = \Drupal\Core\Url::fromRoute('mass_feedback_loop.mass_feedback_loop_author_interface_form')->toString();

      $description = t('Also see: <a href="@negative_feedback_url">Pages with high negative feedback</a> and <a href="@feedback_manager_url">Feedback Manager</a> where you can view, filter and sort feedback submissions.', [
        '@negative_feedback_url' => $negative_feedback_url,
        '@feedback_manager_url' => $feedback_manager_url,
      ]);

      // Append a paragraph below the title.
      $variables['content']['#markup'] .= Markup::create('<p>' . $description . '</p>');
    }
  }
}
