#!/bin/sh

## Description: Run backstop visual regression tests
## Flags: [{"Name":"target","Usage":"The environment to target. Eg feature#, test, or prod.  Default: local"},{"Name":"list","Usage":" Choose a json page to run with backstop (all or post-release) 'all' is default."},{"Name":"viewport","Usage":"Options are desktop, tablet, phone, or all (default)"}]
## Usage: backstop [flags] [args]
## Example: ddev backstop test --target=local --list=all

backstop --config=/src/backstop.js "$@"
