userName:
accessKey:
platforms:
  - os: Windows
    osVersion: 11
    browserName: Chrome
    browserVersion: 103.0
  - os: Windows
    osVersion: 10
    browserName: Firefox
    browserVersion: 102.0
  - os: OS X
    osVersion: Big Sur
    browserName: Safari
    browserVersion: 14.1
parallelsPerPlatform: 1
browserstackLocal: true
buildName: openmass-build-4
projectName: Openmass3
debug: false
percy: true
percyCaptureMode: manual
