<?php

/**
 * @file
 * Contains mass_search.module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_help().
 */
function mass_search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mass_search module.
    case 'help.page.mass_search':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Embeds google custom search engine elements (forms, results, promotions, autocomplete) using javascript') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments().
 *
 * Attach module mass_search global js + css for google api js and
 * custom search header form on every page.
 */
function mass_search_page_attachments(array &$attachments) {
  // Unconditionally attach the search form js + css globally.
  $attachments['#attached']['library'][] = 'mass_search/google-cse';
}

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function mass_search_menu_link_content_access(EntityInterface $entity, string $operation, AccountInterface $account) {
  // Allow footer menus to be viewable by all for jsonapi to work.
  $allowed_menus = [
    'footer-1',
    'footer-2',
    'footer-3',
  ];
  if ($operation === 'view' && in_array($entity->menu_name->value, $allowed_menus)) {
    return AccessResult::allowed();
  }
  return AccessResult::neutral();
}
