<?php

declare(strict_types=1);

namespace PHPSTORM_META {

  // Access token.
  registerArgumentsSet('fields_access_token',
    'id',
    'uuid',
    'user_id',
    'value',
    'expire',
    'entity_type',
    'entity_id',
    'created',
    'changed',
  );
  expectedArguments(\Drupal\access_unpublished\Entity\AccessToken::set(), 0, argumentsSet('fields_access_token'));
  expectedArguments(\Drupal\access_unpublished\Entity\AccessToken::get(), 0, argumentsSet('fields_access_token'));
  expectedArguments(\Drupal\access_unpublished\Entity\AccessToken::hasField(), 0, argumentsSet('fields_access_token'));
  expectedArguments(\Drupal\access_unpublished\AccessTokenInterface::set(), 0, argumentsSet('fields_access_token'));
  expectedArguments(\Drupal\access_unpublished\AccessTokenInterface::get(), 0, argumentsSet('fields_access_token'));
  expectedArguments(\Drupal\access_unpublished\AccessTokenInterface::hasField(), 0, argumentsSet('fields_access_token'));

  // Contact message.
  registerArgumentsSet('fields_contact_message',
    'uuid',
    'langcode',
    'contact_form',
    'name',
    'mail',
    'subject',
    'message',
    'copy',
    'recipient',
    'field_content_flagged',
    'field_reason_flagged',
  );
  expectedArguments(\Drupal\contact\Entity\Message::set(), 0, argumentsSet('fields_contact_message'));
  expectedArguments(\Drupal\contact\Entity\Message::get(), 0, argumentsSet('fields_contact_message'));
  expectedArguments(\Drupal\contact\Entity\Message::hasField(), 0, argumentsSet('fields_contact_message'));
  expectedArguments(\Drupal\contact\MessageInterface::set(), 0, argumentsSet('fields_contact_message'));
  expectedArguments(\Drupal\contact\MessageInterface::get(), 0, argumentsSet('fields_contact_message'));
  expectedArguments(\Drupal\contact\MessageInterface::hasField(), 0, argumentsSet('fields_contact_message'));

  // Content moderation state.
  registerArgumentsSet('fields_content_moderation_state',
    'id',
    'uuid',
    'revision_id',
    'langcode',
    'uid',
    'workflow',
    'moderation_state',
    'content_entity_type_id',
    'content_entity_id',
    'content_entity_revision_id',
    'default_langcode',
    'revision_default',
    'revision_translation_affected',
  );
  expectedArguments(\Drupal\content_moderation\Entity\ContentModerationState::set(), 0, argumentsSet('fields_content_moderation_state'));
  expectedArguments(\Drupal\content_moderation\Entity\ContentModerationState::get(), 0, argumentsSet('fields_content_moderation_state'));
  expectedArguments(\Drupal\content_moderation\Entity\ContentModerationState::hasField(), 0, argumentsSet('fields_content_moderation_state'));

  // Crop.
  registerArgumentsSet('fields_crop',
    'cid',
    'uuid',
    'vid',
    'type',
    'langcode',
    'entity_id',
    'entity_type',
    'uri',
    'height',
    'width',
    'x',
    'y',
    'revision_timestamp',
    'revision_uid',
    'revision_log',
    'default_langcode',
    'revision_default',
    'revision_translation_affected',
  );
  expectedArguments(\Drupal\crop\Entity\Crop::set(), 0, argumentsSet('fields_crop'));
  expectedArguments(\Drupal\crop\Entity\Crop::get(), 0, argumentsSet('fields_crop'));
  expectedArguments(\Drupal\crop\Entity\Crop::hasField(), 0, argumentsSet('fields_crop'));
  expectedArguments(\Drupal\crop\CropInterface::set(), 0, argumentsSet('fields_crop'));
  expectedArguments(\Drupal\crop\CropInterface::get(), 0, argumentsSet('fields_crop'));
  expectedArguments(\Drupal\crop\CropInterface::hasField(), 0, argumentsSet('fields_crop'));

  // Fake entity type.
  registerArgumentsSet('fields_entity_embed_fake_entity',
  );
  expectedArguments(\Drupal\entity_embed\Entity\EntityEmbedFakeEntity::set(), 0, argumentsSet('fields_entity_embed_fake_entity'));
  expectedArguments(\Drupal\entity_embed\Entity\EntityEmbedFakeEntity::get(), 0, argumentsSet('fields_entity_embed_fake_entity'));
  expectedArguments(\Drupal\entity_embed\Entity\EntityEmbedFakeEntity::hasField(), 0, argumentsSet('fields_entity_embed_fake_entity'));

  // Microsite.
  registerArgumentsSet('fields_entity_hierarchy_microsite',
    'id',
    'uuid',
    'name',
    'home',
    'generate_menu',
    'logo',
    'field_microsites_key_message',
  );
  expectedArguments(\Drupal\entity_hierarchy_microsite\Entity\Microsite::set(), 0, argumentsSet('fields_entity_hierarchy_microsite'));
  expectedArguments(\Drupal\entity_hierarchy_microsite\Entity\Microsite::get(), 0, argumentsSet('fields_entity_hierarchy_microsite'));
  expectedArguments(\Drupal\entity_hierarchy_microsite\Entity\Microsite::hasField(), 0, argumentsSet('fields_entity_hierarchy_microsite'));

  // Microsite menu override.
  registerArgumentsSet('fields_eh_microsite_menu_override',
    'id',
    'uuid',
    'title',
    'weight',
    'expanded',
    'enabled',
    'parent',
    'target',
  );
  expectedArguments(\Drupal\entity_hierarchy_microsite\Entity\MicrositeMenuItemOverride::set(), 0, argumentsSet('fields_eh_microsite_menu_override'));
  expectedArguments(\Drupal\entity_hierarchy_microsite\Entity\MicrositeMenuItemOverride::get(), 0, argumentsSet('fields_eh_microsite_menu_override'));
  expectedArguments(\Drupal\entity_hierarchy_microsite\Entity\MicrositeMenuItemOverride::hasField(), 0, argumentsSet('fields_eh_microsite_menu_override'));

  // File.
  registerArgumentsSet('fields_file',
    'fid',
    'uuid',
    'langcode',
    'uid',
    'filename',
    'uri',
    'filemime',
    'filesize',
    'status',
    'created',
    'changed',
  );
  expectedArguments(\Drupal\file\Entity\File::set(), 0, argumentsSet('fields_file'));
  expectedArguments(\Drupal\file\Entity\File::get(), 0, argumentsSet('fields_file'));
  expectedArguments(\Drupal\file\Entity\File::hasField(), 0, argumentsSet('fields_file'));
  expectedArguments(\Drupal\file\FileInterface::set(), 0, argumentsSet('fields_file'));
  expectedArguments(\Drupal\file\FileInterface::get(), 0, argumentsSet('fields_file'));
  expectedArguments(\Drupal\file\FileInterface::hasField(), 0, argumentsSet('fields_file'));

  // Flagging.
  registerArgumentsSet('fields_flagging',
    'id',
    'uuid',
    'flag_id',
    'entity_type',
    'entity_id',
    'global',
    'uid',
    'session_id',
    'created',
  );
  expectedArguments(\Drupal\flag\Entity\Flagging::set(), 0, argumentsSet('fields_flagging'));
  expectedArguments(\Drupal\flag\Entity\Flagging::get(), 0, argumentsSet('fields_flagging'));
  expectedArguments(\Drupal\flag\Entity\Flagging::hasField(), 0, argumentsSet('fields_flagging'));
  expectedArguments(\Drupal\flag\FlaggingInterface::set(), 0, argumentsSet('fields_flagging'));
  expectedArguments(\Drupal\flag\FlaggingInterface::get(), 0, argumentsSet('fields_flagging'));
  expectedArguments(\Drupal\flag\FlaggingInterface::hasField(), 0, argumentsSet('fields_flagging'));

  // User Reference Access.
  registerArgumentsSet('fields_user_ref_access',
    'id',
    'uuid',
    'user_id',
    'additional_users',
    'enabled',
    'entity_type',
    'entity_id',
    'created',
    'changed',
  );
  expectedArguments(\Drupal\mass_entityaccess_userreference\Entity\UserRefAccess::set(), 0, argumentsSet('fields_user_ref_access'));
  expectedArguments(\Drupal\mass_entityaccess_userreference\Entity\UserRefAccess::get(), 0, argumentsSet('fields_user_ref_access'));
  expectedArguments(\Drupal\mass_entityaccess_userreference\Entity\UserRefAccess::hasField(), 0, argumentsSet('fields_user_ref_access'));

  // Media.
  registerArgumentsSet('fields_media',
    'mid',
    'uuid',
    'vid',
    'langcode',
    'bundle',
    'revision_created',
    'revision_user',
    'revision_log_message',
    'status',
    'uid',
    'name',
    'thumbnail',
    'created',
    'changed',
    'default_langcode',
    'revision_default',
    'revision_translation_affected',
    'search',
    'field_category',
    'field_collections',
    'field_description',
    'field_document_label',
    'field_document_listing_desc',
    'field_document_type',
    'field_file_mime',
    'field_internal_notes',
    'field_language',
    'field_media_english_version',
    'field_media_video_embed_field',
    'field_organizations',
    'field_size',
    'field_start_date',
    'field_title',
    'field_upload_file',
    'field_video_description',
    'field_video_transcript',
  );
  expectedArguments(\Drupal\media\Entity\Media::set(), 0, argumentsSet('fields_media'));
  expectedArguments(\Drupal\media\Entity\Media::get(), 0, argumentsSet('fields_media'));
  expectedArguments(\Drupal\media\Entity\Media::hasField(), 0, argumentsSet('fields_media'));
  expectedArguments(\Drupal\media\MediaInterface::set(), 0, argumentsSet('fields_media'));
  expectedArguments(\Drupal\media\MediaInterface::get(), 0, argumentsSet('fields_media'));
  expectedArguments(\Drupal\media\MediaInterface::hasField(), 0, argumentsSet('fields_media'));

  // Content.
  registerArgumentsSet('fields_node',
    'nid',
    'uuid',
    'vid',
    'langcode',
    'type',
    'revision_timestamp',
    'revision_uid',
    'revision_log',
    'status',
    'uid',
    'title',
    'created',
    'changed',
    'promote',
    'sticky',
    'default_langcode',
    'revision_default',
    'revision_translation_affected',
    'search',
    'search_nosnippet',
    'rh_action',
    'rh_redirect',
    'rh_redirect_response',
    'rh_redirect_fallback_action',
    'content_translation_source',
    'content_translation_outdated',
    'body',
    'field_accessibility',
    'field_action_banner',
    'field_action_details',
    'field_action_header',
    'field_action_parent',
    'field_action_sidebar',
    'field_add_video',
    'field_advisory_date',
    'field_advisory_download',
    'field_advisory_footnotes',
    'field_advisory_issuer',
    'field_advisory_links',
    'field_advisory_listing_desc',
    'field_advisory_metatags',
    'field_advisory_overview',
    'field_advisory_publish_state_tax',
    'field_advisory_ref_contact',
    'field_advisory_ref_sources',
    'field_advisory_section',
    'field_advisory_type_tax',
    'field_alert',
    'field_alert_display',
    'field_alert_dropdown',
    'field_alert_hide_message',
    'field_alert_link',
    'field_alert_node_timestamp',
    'field_alert_ref_contact',
    'field_alert_related_links_5',
    'field_alert_severity',
    'field_alert_text',
    'field_alert_title_link',
    'field_alert_title_link_target',
    'field_api_serv_card_description',
    'field_api_serv_card_link',
    'field_api_serv_card_machine_name',
    'field_api_srv_card_idv_ret_urls',
    'field_api_srv_card_logout_locale',
    'field_api_srv_card_logout_urls',
    'field_api_srv_card_ret_locale',
    'field_api_srv_card_status',
    'field_api_srv_card_tenant',
    'field_application_login_links',
    'field_aria_label',
    'field_author',
    'field_bands',
    'field_banner_image',
    'field_bg_narrow',
    'field_bg_wide',
    'field_billing_organization',
    'field_binder_appendix',
    'field_binder_banner_image',
    'field_binder_binder_type',
    'field_binder_data_type',
    'field_binder_date_published',
    'field_binder_last_updated',
    'field_binder_metatags',
    'field_binder_overview',
    'field_binder_pages',
    'field_binder_ref_organization',
    'field_binder_related',
    'field_binder_serial_number',
    'field_binder_short_desc',
    'field_binder_volume',
    'field_branch_disclaimer',
    'field_campaign_landing_metatags',
    'field_career_opportunities',
    'field_collections',
    'field_constituent_communication',
    'field_contact',
    'field_contact_more_info_link',
    'field_contact_source',
    'field_curatedlist_lede',
    'field_curatedlist_list_section',
    'field_curatedlist_metatags',
    'field_curatedlist_overview',
    'field_customize_header_text',
    'field_data_flag',
    'field_data_format',
    'field_data_resource_type',
    'field_data_search_content',
    'field_data_topic',
    'field_date_published',
    'field_decision_actions',
    'field_decision_date',
    'field_decision_docket_number',
    'field_decision_download',
    'field_decision_footnotes',
    'field_decision_listing_desc',
    'field_decision_location',
    'field_decision_metatags',
    'field_decision_overview',
    'field_decision_participants',
    'field_decision_ref_contact',
    'field_decision_ref_organization',
    'field_decision_ref_type',
    'field_decision_related',
    'field_decision_root_ref',
    'field_decision_section',
    'field_decision_sources',
    'field_decision_tree_metatags',
    'field_description',
    'field_details_data_type',
    'field_disclaimer',
    'field_display_short_description',
    'field_display_title',
    'field_downloads',
    'field_downloads_header',
    'field_english_version',
    'field_environment',
    'field_error_code',
    'field_error_label',
    'field_error_message',
    'field_error_title',
    'field_event_address_type',
    'field_event_agenda_download',
    'field_event_capacity',
    'field_event_contact_general',
    'field_event_date',
    'field_event_description',
    'field_event_fees',
    'field_event_image',
    'field_event_lede',
    'field_event_links',
    'field_event_link_sign_up',
    'field_event_logo',
    'field_event_meeting_agenda_sect',
    'field_event_meeting_minutes',
    'field_event_metatags',
    'field_event_minutes_download',
    'field_event_participating_orgs',
    'field_event_posted_date',
    'field_event_public_testimony',
    'field_event_rain_date',
    'field_event_ref_contact',
    'field_event_ref_downloads',
    'field_event_ref_event_2',
    'field_event_ref_parents',
    'field_event_ref_unique_address',
    'field_event_time',
    'field_event_type_list',
    'field_event_you_will_need',
    'field_executive_order_adjustment',
    'field_executive_order_contact',
    'field_executive_order_date',
    'field_executive_order_downloads',
    'field_executive_order_issuer',
    'field_executive_order_mass_regis',
    'field_executive_order_metatags',
    'field_executive_order_number',
    'field_executive_order_overview',
    'field_executive_order_related',
    'field_executive_title',
    'field_exec_order_listing_desc',
    'field_externaldata_description',
    'field_externaldata_url',
    'field_external_organization',
    'field_external_url',
    'field_feedback_com_link',
    'field_fees_header',
    'field_fee_fee',
    'field_fee_name',
    'field_fee_unit',
    'field_footnotes',
    'field_form_embed',
    'field_form_lede',
    'field_form_listing_desc',
    'field_form_platform',
    'field_form_ref_contacts_3',
    'field_form_url',
    'field_form_you_will',
    'field_get_updates_links',
    'field_glossaries',
    'field_guide_page_bg_wide',
    'field_guide_page_lede',
    'field_guide_page_metatags',
    'field_guide_page_related_guides',
    'field_guide_page_sections',
    'field_header',
    'field_header_cta',
    'field_helpful_links',
    'field_hide_feedback_component',
    'field_hide_short_description',
    'field_hide_table_of_contents',
    'field_how_to_contacts_3',
    'field_how_to_fee_description',
    'field_how_to_files',
    'field_how_to_lede',
    'field_how_to_links_5',
    'field_how_to_link_1',
    'field_how_to_metatags',
    'field_how_to_methods_5',
    'field_how_to_more_info',
    'field_how_to_next_steps',
    'field_how_to_ref_fees',
    'field_how_to_taxo_action_type',
    'field_how_to_time',
    'field_how_to_what_you_need',
    'field_icon_term',
    'field_iframe',
    'field_image_credit',
    'field_include_search',
    'field_infodetails_metatags',
    'field_info_details_date_publishe',
    'field_info_details_header_media',
    'field_info_details_last_updated',
    'field_info_details_related',
    'field_info_details_sections',
    'field_info_detail_overview',
    'field_intended_audience',
    'field_interstitial_checkbox_msg',
    'field_label',
    'field_lede',
    'field_links',
    'field_list_data_type',
    'field_list_directory_section',
    'field_list_type',
    'field_location_activity_detail',
    'field_location_all_activities',
    'field_location_details_lede',
    'field_location_details_links_5',
    'field_location_details_metatags',
    'field_location_details_sections',
    'field_location_facilities',
    'field_location_icons',
    'field_location_icons_park',
    'field_location_metatags',
    'field_location_more_information',
    'field_location_subtitle',
    'field_location_type',
    'field_login_links_options',
    'field_log_in_links',
    'field_manage_your_account',
    'field_manage_your_account_header',
    'field_medium_image',
    'field_message',
    'field_metatags',
    'field_meta_description',
    'field_migrated_node_id',
    'field_more_about_agency_link',
    'field_more_about_leadership',
    'field_more_info',
    'field_more_info_header',
    'field_multiple_answers',
    'field_news_body',
    'field_news_date',
    'field_news_image',
    'field_news_lede',
    'field_news_links',
    'field_news_location',
    'field_news_media_contac',
    'field_news_metatags',
    'field_news_sections',
    'field_news_signees',
    'field_news_summary',
    'field_news_type',
    'field_news_video',
    'field_next_steps_header',
    'field_organizations',
    'field_organization_sections',
    'field_organization_type',
    'field_org_always_show_help_page',
    'field_org_directory_page',
    'field_org_no_search_filter',
    'field_org_page_thumbnail',
    'field_org_sentence_phrasing',
    'field_overview',
    'field_page_template',
    'field_parent',
    'field_parking',
    'field_person_bio',
    'field_person_email',
    'field_person_first_name',
    'field_person_headshot',
    'field_person_last_name',
    'field_person_phone',
    'field_person_profile_image',
    'field_person_ref_org',
    'field_person_role_title',
    'field_person_type',
    'field_photo',
    'field_plain_description',
    'field_primary_parent',
    'field_public_records_link',
    'field_publish_bio_page',
    'field_ref_address',
    'field_ref_contact_info',
    'field_ref_contact_info_1',
    'field_ref_fax',
    'field_ref_fax_number',
    'field_ref_hours',
    'field_ref_links',
    'field_ref_phone',
    'field_ref_phone_number',
    'field_ref_single_address',
    'field_regluation_official_ver',
    'field_regulation_agency_cmr',
    'field_regulation_cmr_chapter',
    'field_regulation_contact',
    'field_regulation_download',
    'field_regulation_last_updated',
    'field_regulation_link_org',
    'field_regulation_listing_desc',
    'field_regulation_metatags',
    'field_regulation_ref_state_tax',
    'field_regulation_reg_authority',
    'field_regulation_related',
    'field_regulation_section',
    'field_regulation_short_descr',
    'field_regulation_title',
    'field_related_content',
    'field_related_links',
    'field_related_locations',
    'field_restrictions',
    'field_restrict_link_management',
    'field_restrict_orgs_field',
    'field_reusable_label',
    'field_rules_adopted_date',
    'field_rules_courts',
    'field_rules_download',
    'field_rules_effective_date',
    'field_rules_footnotes',
    'field_rules_listing_desc',
    'field_rules_metatags',
    'field_rules_overview',
    'field_rules_referenced_sources',
    'field_rules_ref_contact',
    'field_rules_related',
    'field_rules_related_collections',
    'field_rules_section',
    'field_rules_standing',
    'field_rules_status',
    'field_rules_subheading',
    'field_rules_type',
    'field_rules_updates',
    'field_search',
    'field_secondary_person_bio',
    'field_sections',
    'field_services',
    'field_services_social_links',
    'field_service_bg_wide',
    'field_service_body',
    'field_service_eligibility_info',
    'field_service_lede',
    'field_service_metatags',
    'field_service_ref_guide_page_1',
    'field_service_ref_services_6',
    'field_service_sections',
    'field_service_video',
    'field_short_bio',
    'field_short_desc',
    'field_short_title',
    'field_sitewide_alert',
    'field_sitewide_alert_severity',
    'field_social_links',
    'field_start_button',
    'field_subtype',
    'field_sub_brand',
    'field_sub_title',
    'field_target_organization',
    'field_target_page',
    'field_terms',
    'field_title_sub_text',
    'field_topic_callout_links',
    'field_topic_content_cards',
    'field_topic_lede',
    'field_topic_metatags',
    'field_topic_ref_related_topics',
    'field_updated_date',
    'field_urgent_warning',
    'field_use_alt_header',
    'field_what_you_need_header',
  );
  expectedArguments(\Drupal\node\Entity\Node::set(), 0, argumentsSet('fields_node'));
  expectedArguments(\Drupal\node\Entity\Node::get(), 0, argumentsSet('fields_node'));
  expectedArguments(\Drupal\node\Entity\Node::hasField(), 0, argumentsSet('fields_node'));
  expectedArguments(\Drupal\node\NodeInterface::set(), 0, argumentsSet('fields_node'));
  expectedArguments(\Drupal\node\NodeInterface::get(), 0, argumentsSet('fields_node'));
  expectedArguments(\Drupal\node\NodeInterface::hasField(), 0, argumentsSet('fields_node'));

  // Paragraph.
  registerArgumentsSet('fields_paragraph',
    'id',
    'uuid',
    'revision_id',
    'langcode',
    'type',
    'status',
    'created',
    'parent_id',
    'parent_type',
    'parent_field_name',
    'behavior_settings',
    'default_langcode',
    'revision_default',
    'revision_translation_affected',
    'field_2up_featured_item',
    'field_2up_featured_item_2',
    'field_3_up_rows',
    'field_action_step_numbered_items',
    'field_activities',
    'field_address',
    'field_address_address',
    'field_address_label',
    'field_address_ref',
    'field_address_text',
    'field_add_heading_description',
    'field_adjustment_type',
    'field_adjustment_type_link',
    'field_adjustment_type_term',
    'field_advisory_display_name',
    'field_advisory_person_ref',
    'field_advisory_section_body',
    'field_advisory_section_title',
    'field_alert_text',
    'field_alignment',
    'field_answer_explainer',
    'field_answer_path',
    'field_answer_text',
    'field_area_action_ref',
    'field_aspect_ratio',
    'field_background_color',
    'field_background_type',
    'field_band',
    'field_board_members',
    'field_body',
    'field_branch_locations',
    'field_button',
    'field_campaign_code_overview',
    'field_campaign_custom_html',
    'field_campaign_description',
    'field_caption',
    'field_card',
    'field_card_content',
    'field_card_eyebrow',
    'field_card_header',
    'field_card_link',
    'field_caspio_admin_title',
    'field_caspio_data_identifier',
    'field_collection',
    'field_component_add_separator',
    'field_contact',
    'field_contact_directions_link',
    'field_contact_group_layout',
    'field_contact_info',
    'field_contact_values_to_display',
    'field_content',
    'field_content_card_category',
    'field_content_card_link_cards',
    'field_csvtable_caption',
    'field_csvtable_display_size',
    'field_csvtable_title',
    'field_csv_file',
    'field_decision_participant_name',
    'field_decision_section_body',
    'field_decision_section_title',
    'field_description',
    'field_display_type',
    'field_downloads',
    'field_email',
    'field_emergency_alert_content',
    'field_emergency_alert_link',
    'field_emergency_alert_link_type',
    'field_emergency_alert_message',
    'field_event_agenda_body',
    'field_event_agenda_title',
    'field_event_minutes_body',
    'field_event_minutes_title',
    'field_event_quantity',
    'field_external_org_description',
    'field_external_org_name',
    'field_external_org_photo',
    'field_eyebrow',
    'field_fax',
    'field_featured',
    'field_featured_board_members',
    'field_featured_content',
    'field_featured_item_highlight',
    'field_featured_item_image',
    'field_featured_item_link',
    'field_featured_item_mosaic_items',
    'field_featured_message_content',
    'field_featured_message_heading',
    'field_featured_message_link',
    'field_featured_topics_topics',
    'field_file_download_single',
    'field_flexible_link_group_desc',
    'field_flexible_link_group_title',
    'field_footnotes_desc',
    'field_footnotes_title',
    'field_full_bleed_ref',
    'field_full_width_featured_item',
    'field_geofield',
    'field_group_expanded',
    'field_guide_ref_contacts_3',
    'field_guide_section_alert_text',
    'field_guide_section_body',
    'field_guide_section_body_first',
    'field_guide_section_body_second',
    'field_guide_section_body_third',
    'field_guide_section_downloads',
    'field_guide_section_heading_1',
    'field_guide_section_heading_2',
    'field_guide_section_heading_3',
    'field_guide_section_label',
    'field_guide_section_link',
    'field_guide_section_links_4',
    'field_guide_section_name',
    'field_guide_section_stat',
    'field_guide_section_time',
    'field_heading',
    'field_height',
    'field_hide_heading',
    'field_hide_in_org_navigation',
    'field_home_bckgrnd_img_paragraph',
    'field_hours',
    'field_hours_description',
    'field_hours_group_title',
    'field_hours_structured',
    'field_icon',
    'field_icon_link',
    'field_iframe_accessibility_title',
    'field_iframe_admin_title',
    'field_iframe_alignment',
    'field_iframe_caption',
    'field_iframe_display_size',
    'field_iframe_height_config',
    'field_iframe_wrapping',
    'field_image',
    'field_image_administrative_title',
    'field_image_alignment',
    'field_image_caption',
    'field_image_credit_caption',
    'field_image_credit_link',
    'field_image_credit_source',
    'field_image_display_size',
    'field_image_wrapping',
    'field_issuer_content_id',
    'field_issuer_display_name',
    'field_issuer_issuers',
    'field_issuer_title',
    'field_label',
    'field_lat_long',
    'field_lede',
    'field_link',
    'field_links_documents',
    'field_links_downloads_down',
    'field_links_downloads_header',
    'field_links_downloads_link',
    'field_link_group',
    'field_link_group_link',
    'field_link_single',
    'field_link_six',
    'field_listdynamic_description',
    'field_listdynamic_label',
    'field_listdynamic_sort',
    'field_listdynamic_title',
    'field_listitemdoc_desc_manual',
    'field_listitemdoc_desc_type',
    'field_listitemlink_desc_manual',
    'field_listitemlink_desc_type',
    'field_listitemlink_item',
    'field_liststaticdoc_item',
    'field_liststatic_description',
    'field_liststatic_items',
    'field_liststatic_title',
    'field_list_dynamic_desc_setting',
    'field_location_button_label',
    'field_location_button_short_desc',
    'field_location_info_ref',
    'field_main',
    'field_main_heading',
    'field_manage_account_link',
    'field_manage_account_link_body',
    'field_map',
    'field_map_locations',
    'field_media_contact_email',
    'field_media_contact_name',
    'field_media_contact_phone',
    'field_media_contact_ref_person',
    'field_media_display',
    'field_method_details',
    'field_method_type',
    'field_more_info_text',
    'field_more_info_title',
    'field_mosaic_heading',
    'field_name',
    'field_next_step_details',
    'field_next_step_downloads',
    'field_next_step_link',
    'field_next_step_title',
    'field_number_of_news_items',
    'field_org_featured_news_items',
    'field_org_grid_org',
    'field_org_navigation_jump_link_t',
    'field_org_ref_locations',
    'field_org_show_news_images',
    'field_page_group_name',
    'field_page_group_page',
    'field_page_page',
    'field_para_icon_term',
    'field_person',
    'field_phone',
    'field_position_is_vacant',
    'field_quote',
    'field_read_more_page',
    'field_ref_location_details_page',
    'field_ref_orgs',
    'field_ref_participant_type',
    'field_regulation_section_body',
    'field_regulation_section_title',
    'field_related_content',
    'field_related_content_link',
    'field_related_organization_type',
    'field_reusable_paragraph',
    'field_rich_text_description',
    'field_right_rail',
    'field_rules_section_body',
    'field_rules_section_title',
    'field_rules_update_note',
    'field_rules_update_url',
    'field_search_button_label',
    'field_search_footer',
    'field_search_heading',
    'field_search_querystring',
    'field_search_query_param_name',
    'field_search_related_info',
    'field_search_site_url',
    'field_search_type',
    'field_section_background_color',
    'field_section_body',
    'field_section_downloads',
    'field_section_heading_text_body',
    'field_section_heading_text_head',
    'field_section_key_actions',
    'field_section_links',
    'field_section_long_form_addition',
    'field_section_long_form_content',
    'field_section_long_form_heading',
    'field_section_style',
    'field_section_text_overlay_color',
    'field_section_title',
    'field_service_section_content',
    'field_service_section_heading',
    'field_service_section_link',
    'field_sitewide_alert_content',
    'field_sitewide_alert_link',
    'field_sitewide_alert_link_type',
    'field_sitewide_alert_message',
    'field_sitewide_alert_timestamp',
    'field_slideshow',
    'field_start_button_branch',
    'field_start_button_label',
    'field_stat',
    'field_state_org_description',
    'field_state_org_name',
    'field_state_org_photo',
    'field_state_org_photo_url',
    'field_state_org_ref_org',
    'field_stat_wrapping',
    'field_subtitle',
    'field_sub_heading',
    'field_summary',
    'field_tableau_embed_type',
    'field_tableau_url_token',
    'field_tabl_administrative_title',
    'field_tabl_alignment',
    'field_tabl_caption',
    'field_tabl_display_size',
    'field_tabl_wrapping',
    'field_teaser',
    'field_text_overlay_color',
    'field_time',
    'field_time_callout_text',
    'field_time_frame',
    'field_title',
    'field_topic_name_only',
    'field_two_column',
    'field_type',
    'field_url',
    'field_use_half_image',
    'field_use_image_cards',
    'field_use_two_columns',
    'field_verify_iframe_100_confirm',
    'field_video',
    'field_video_caption',
    'field_video_header_bg_color',
    'field_video_id',
    'field_video_section_bg_color',
    'field_video_source',
    'field_wwyltd_heading',
    'field_wwyltd_more_services',
    'field_wwyltd_top_s_links',
  );
  expectedArguments(\Drupal\paragraphs\Entity\Paragraph::set(), 0, argumentsSet('fields_paragraph'));
  expectedArguments(\Drupal\paragraphs\Entity\Paragraph::get(), 0, argumentsSet('fields_paragraph'));
  expectedArguments(\Drupal\paragraphs\Entity\Paragraph::hasField(), 0, argumentsSet('fields_paragraph'));
  expectedArguments(\Drupal\paragraphs\ParagraphInterface::set(), 0, argumentsSet('fields_paragraph'));
  expectedArguments(\Drupal\paragraphs\ParagraphInterface::get(), 0, argumentsSet('fields_paragraph'));
  expectedArguments(\Drupal\paragraphs\ParagraphInterface::hasField(), 0, argumentsSet('fields_paragraph'));

  // Paragraphs library item.
  registerArgumentsSet('fields_paragraphs_library_item',
    'id',
    'uuid',
    'revision_id',
    'langcode',
    'revision_created',
    'revision_uid',
    'revision_log',
    'status',
    'label',
    'paragraphs',
    'created',
    'changed',
    'uid',
    'default_langcode',
    'revision_default',
    'revision_translation_affected',
  );
  expectedArguments(\Drupal\paragraphs_library\Entity\LibraryItem::set(), 0, argumentsSet('fields_paragraphs_library_item'));
  expectedArguments(\Drupal\paragraphs_library\Entity\LibraryItem::get(), 0, argumentsSet('fields_paragraphs_library_item'));
  expectedArguments(\Drupal\paragraphs_library\Entity\LibraryItem::hasField(), 0, argumentsSet('fields_paragraphs_library_item'));
  expectedArguments(\Drupal\paragraphs_library\LibraryItemInterface::set(), 0, argumentsSet('fields_paragraphs_library_item'));
  expectedArguments(\Drupal\paragraphs_library\LibraryItemInterface::get(), 0, argumentsSet('fields_paragraphs_library_item'));
  expectedArguments(\Drupal\paragraphs_library\LibraryItemInterface::hasField(), 0, argumentsSet('fields_paragraphs_library_item'));

  // URL alias.
  registerArgumentsSet('fields_path_alias',
    'id',
    'uuid',
    'revision_id',
    'langcode',
    'path',
    'alias',
    'status',
    'revision_default',
  );
  expectedArguments(\Drupal\path_alias\Entity\PathAlias::set(), 0, argumentsSet('fields_path_alias'));
  expectedArguments(\Drupal\path_alias\Entity\PathAlias::get(), 0, argumentsSet('fields_path_alias'));
  expectedArguments(\Drupal\path_alias\Entity\PathAlias::hasField(), 0, argumentsSet('fields_path_alias'));
  expectedArguments(\Drupal\path_alias\PathAliasInterface::set(), 0, argumentsSet('fields_path_alias'));
  expectedArguments(\Drupal\path_alias\PathAliasInterface::get(), 0, argumentsSet('fields_path_alias'));
  expectedArguments(\Drupal\path_alias\PathAliasInterface::hasField(), 0, argumentsSet('fields_path_alias'));

  // Redirect.
  registerArgumentsSet('fields_redirect',
    'rid',
    'uuid',
    'hash',
    'type',
    'uid',
    'redirect_source',
    'redirect_redirect',
    'language',
    'status_code',
    'created',
  );
  expectedArguments(\Drupal\redirect\Entity\Redirect::set(), 0, argumentsSet('fields_redirect'));
  expectedArguments(\Drupal\redirect\Entity\Redirect::get(), 0, argumentsSet('fields_redirect'));
  expectedArguments(\Drupal\redirect\Entity\Redirect::hasField(), 0, argumentsSet('fields_redirect'));

  // scheduled transition.
  registerArgumentsSet('fields_scheduled_transition',
    'id',
    'uuid',
    'entity',
    'entity_revision_id',
    'entity_revision_langcode',
    'author',
    'workflow',
    'moderation_state',
    'created',
    'transition_on',
    'locked_on',
    'options',
  );
  expectedArguments(\Drupal\scheduled_transitions\Entity\ScheduledTransition::set(), 0, argumentsSet('fields_scheduled_transition'));
  expectedArguments(\Drupal\scheduled_transitions\Entity\ScheduledTransition::get(), 0, argumentsSet('fields_scheduled_transition'));
  expectedArguments(\Drupal\scheduled_transitions\Entity\ScheduledTransition::hasField(), 0, argumentsSet('fields_scheduled_transition'));

  // Taxonomy term.
  registerArgumentsSet('fields_taxonomy_term',
    'tid',
    'uuid',
    'revision_id',
    'langcode',
    'vid',
    'revision_created',
    'revision_user',
    'revision_log_message',
    'status',
    'name',
    'description',
    'weight',
    'parent',
    'changed',
    'default_langcode',
    'revision_default',
    'revision_translation_affected',
    'rh_action',
    'rh_redirect',
    'rh_redirect_response',
    'rh_redirect_fallback_action',
    'field_additional_no_items_found',
    'field_additional_search_keywords',
    'field_all_collection_breadcrumb',
    'field_billing_account_number',
    'field_billing_customer_code',
    'field_billing_customer_group',
    'field_billing_customer_name',
    'field_collection_logo',
    'field_dataresource_metatag',
    'field_default_sort',
    'field_details_datatype_metatag',
    'field_header_color',
    'field_landing_page',
    'field_list_datatype_metatag',
    'field_organizations',
    'field_primary_parent',
    'field_reusable_label',
    'field_short_description',
    'field_show_only_future_events',
    'field_sort_order',
    'field_sprite_name',
    'field_sprite_type',
    'field_state_organization',
    'field_url_name',
  );
  expectedArguments(\Drupal\taxonomy\Entity\Term::set(), 0, argumentsSet('fields_taxonomy_term'));
  expectedArguments(\Drupal\taxonomy\Entity\Term::get(), 0, argumentsSet('fields_taxonomy_term'));
  expectedArguments(\Drupal\taxonomy\Entity\Term::hasField(), 0, argumentsSet('fields_taxonomy_term'));
  expectedArguments(\Drupal\taxonomy\TermInterface::set(), 0, argumentsSet('fields_taxonomy_term'));
  expectedArguments(\Drupal\taxonomy\TermInterface::get(), 0, argumentsSet('fields_taxonomy_term'));
  expectedArguments(\Drupal\taxonomy\TermInterface::hasField(), 0, argumentsSet('fields_taxonomy_term'));

  // User.
  registerArgumentsSet('fields_user',
    'uid',
    'uuid',
    'langcode',
    'preferred_langcode',
    'preferred_admin_langcode',
    'name',
    'pass',
    'mail',
    'timezone',
    'status',
    'created',
    'changed',
    'access',
    'login',
    'init',
    'roles',
    'default_langcode',
    'api_key',
    'field_approval_notes',
    'field_approved',
    'field_user_org',
    'user_picture',
  );
  expectedArguments(\Drupal\user\Entity\User::set(), 0, argumentsSet('fields_user'));
  expectedArguments(\Drupal\user\Entity\User::get(), 0, argumentsSet('fields_user'));
  expectedArguments(\Drupal\user\Entity\User::hasField(), 0, argumentsSet('fields_user'));
  expectedArguments(\Drupal\user\UserInterface::set(), 0, argumentsSet('fields_user'));
  expectedArguments(\Drupal\user\UserInterface::get(), 0, argumentsSet('fields_user'));
  expectedArguments(\Drupal\user\UserInterface::hasField(), 0, argumentsSet('fields_user'));

  // Custom menu link.
  registerArgumentsSet('fields_menu_link_content',
    'id',
    'uuid',
    'revision_id',
    'langcode',
    'bundle',
    'revision_created',
    'revision_user',
    'revision_log_message',
    'enabled',
    'title',
    'description',
    'menu_name',
    'link',
    'external',
    'rediscover',
    'weight',
    'expanded',
    'parent',
    'changed',
    'default_langcode',
    'revision_default',
    'revision_translation_affected',
  );
  expectedArguments(\Drupal\menu_link_content\Entity\MenuLinkContent::set(), 0, argumentsSet('fields_menu_link_content'));
  expectedArguments(\Drupal\menu_link_content\Entity\MenuLinkContent::get(), 0, argumentsSet('fields_menu_link_content'));
  expectedArguments(\Drupal\menu_link_content\Entity\MenuLinkContent::hasField(), 0, argumentsSet('fields_menu_link_content'));
  expectedArguments(\Drupal\menu_link_content\MenuLinkContentInterface::set(), 0, argumentsSet('fields_menu_link_content'));
  expectedArguments(\Drupal\menu_link_content\MenuLinkContentInterface::get(), 0, argumentsSet('fields_menu_link_content'));
  expectedArguments(\Drupal\menu_link_content\MenuLinkContentInterface::hasField(), 0, argumentsSet('fields_menu_link_content'));

}
