<?php

declare(strict_types=1);

namespace PHPSTORM_META {

  registerArgumentsSet('permissions',
    'Administer Quick Node Clone Settings',
    'access administration pages',
    'access browse_files entity browser pages',
    'access browse_files_modal entity browser pages',
    'access clean file managed config page',
    'access content',
    'access content overview',
    'access data flag fields',
    'access draggableviews',
    'access email address list for alerts config page',
    'access entity usage statistics',
    'access environment indicator',
    'access files overview',
    'access geocoder api endpoints',
    'access header config page',
    'access help pages',
    'access iframe config page',
    'access media overview',
    'access media_browser entity browser pages',
    'access paragraphs_library_items entity browser pages',
    'access security review list',
    'access site in maintenance mode',
    'access site reports',
    'access site-wide contact form',
    'access taxonomy overview',
    'access the custom_html field',
    'access tokens overview',
    'access toolbar',
    'access user contact forms',
    'access user profiles',
    'access video_browser entity browser pages',
    'access_unpublished media document',
    'access_unpublished media media_video',
    'access_unpublished menu_link_content',
    'access_unpublished node action',
    'access_unpublished node advisory',
    'access_unpublished node alert',
    'access_unpublished node api_service_card',
    'access_unpublished node binder',
    'access_unpublished node campaign_landing',
    'access_unpublished node contact_information',
    'access_unpublished node curated_list',
    'access_unpublished node decision',
    'access_unpublished node decision_tree',
    'access_unpublished node decision_tree_branch',
    'access_unpublished node decision_tree_conclusion',
    'access_unpublished node error_page',
    'access_unpublished node event',
    'access_unpublished node executive_order',
    'access_unpublished node external_data_resource',
    'access_unpublished node fee',
    'access_unpublished node form_page',
    'access_unpublished node glossary',
    'access_unpublished node guide_page',
    'access_unpublished node how_to_page',
    'access_unpublished node info_details',
    'access_unpublished node interstitial',
    'access_unpublished node location',
    'access_unpublished node location_details',
    'access_unpublished node news',
    'access_unpublished node org_page',
    'access_unpublished node page',
    'access_unpublished node person',
    'access_unpublished node regulation',
    'access_unpublished node rules',
    'access_unpublished node service_page',
    'access_unpublished node sitewide_alert',
    'access_unpublished node stacked_layout',
    'access_unpublished node topic_page',
    'access_unpublished node utility_drawer',
    'access_unpublished paragraphs_library_item',
    'access_unpublished taxonomy_term action_type',
    'access_unpublished taxonomy_term adjustment_type',
    'access_unpublished taxonomy_term advisory_publish_state',
    'access_unpublished taxonomy_term advisory_type',
    'access_unpublished taxonomy_term announcement_type',
    'access_unpublished taxonomy_term billing_organizations',
    'access_unpublished taxonomy_term binder_type',
    'access_unpublished taxonomy_term collections',
    'access_unpublished taxonomy_term content_type',
    'access_unpublished taxonomy_term data_topic',
    'access_unpublished taxonomy_term decision_participant_type',
    'access_unpublished taxonomy_term decision_type',
    'access_unpublished taxonomy_term document_category',
    'access_unpublished taxonomy_term document_contacts',
    'access_unpublished taxonomy_term document_creators',
    'access_unpublished taxonomy_term document_other_type',
    'access_unpublished taxonomy_term document_subjects',
    'access_unpublished taxonomy_term document_tags',
    'access_unpublished taxonomy_term event_type',
    'access_unpublished taxonomy_term icons',
    'access_unpublished taxonomy_term label',
    'access_unpublished taxonomy_term language',
    'access_unpublished taxonomy_term license',
    'access_unpublished taxonomy_term location_activities',
    'access_unpublished taxonomy_term location_icon',
    'access_unpublished taxonomy_term location_icon_park',
    'access_unpublished taxonomy_term organization_type',
    'access_unpublished taxonomy_term rules_of_court_standing_order',
    'access_unpublished taxonomy_term rules_of_court_type',
    'access_unpublished taxonomy_term tags',
    'access_unpublished taxonomy_term tx_data_resource_type',
    'access_unpublished taxonomy_term tx_details_data_type',
    'access_unpublished taxonomy_term tx_list_data_type',
    'access_unpublished taxonomy_term type',
    'access_unpublished taxonomy_term user_organization',
    'add scheduled transitions media document',
    'add scheduled transitions node action',
    'add scheduled transitions node advisory',
    'add scheduled transitions node alert',
    'add scheduled transitions node binder',
    'add scheduled transitions node campaign_landing',
    'add scheduled transitions node contact_information',
    'add scheduled transitions node curated_list',
    'add scheduled transitions node decision',
    'add scheduled transitions node decision_tree',
    'add scheduled transitions node decision_tree_branch',
    'add scheduled transitions node decision_tree_conclusion',
    'add scheduled transitions node event',
    'add scheduled transitions node executive_order',
    'add scheduled transitions node external_data_resource',
    'add scheduled transitions node fee',
    'add scheduled transitions node form_page',
    'add scheduled transitions node guide_page',
    'add scheduled transitions node how_to_page',
    'add scheduled transitions node info_details',
    'add scheduled transitions node location',
    'add scheduled transitions node location_details',
    'add scheduled transitions node news',
    'add scheduled transitions node org_page',
    'add scheduled transitions node page',
    'add scheduled transitions node person',
    'add scheduled transitions node regulation',
    'add scheduled transitions node rules',
    'add scheduled transitions node service_page',
    'add scheduled transitions node sitewide_alert',
    'add scheduled transitions node stacked_layout',
    'add scheduled transitions node topic_page',
    'add special paragraphs to info_details',
    'administer account settings',
    'administer actions',
    'administer akamai',
    'administer blocks',
    'administer clamav',
    'administer contact forms',
    'administer contact_form labels',
    'administer contact_message display',
    'administer contact_message fields',
    'administer contact_message form display',
    'administer content translation',
    'administer content types',
    'administer crop',
    'administer crop types',
    'administer crop_type labels',
    'administer display modes',
    'administer editoria11y checker',
    'administer embed buttons',
    'administer entity browsers',
    'administer entity hierarchy microsites',
    'administer entity usage',
    'administer entity_hierarchy_microsite display',
    'administer entity_hierarchy_microsite fields',
    'administer entity_hierarchy_microsite form display',
    'administer environment indicator settings',
    'administer filters',
    'administer flag labels',
    'administer flagging display',
    'administer flagging fields',
    'administer flagging form display',
    'administer flaggings',
    'administer flags',
    'administer form for alert block',
    'administer form for node feedback block',
    'administer form for report authors',
    'administer form for right sidebar block',
    'administer form for support block',
    'administer google_tag_container',
    'administer iframe resizer',
    'administer image styles',
    'administer key configuration overrides',
    'administer keys',
    'administer languages',
    'administer linkit profiles',
    'administer mailchimp transactional',
    'administer mailchimp transactional templates',
    'administer mass_bigquery configuration',
    'administer media',
    'administer media display',
    'administer media fields',
    'administer media form display',
    'administer media types',
    'administer media_type labels',
    'administer menu',
    'administer meta tags',
    'administer modules',
    'administer node display',
    'administer node fields',
    'administer node form display',
    'administer node_type labels',
    'administer nodes',
    'administer openid connect clients',
    'administer paragraph display',
    'administer paragraph fields',
    'administer paragraph form display',
    'administer paragraphs library',
    'administer paragraphs settings',
    'administer paragraphs types',
    'administer paragraphs_library_item display',
    'administer paragraphs_library_item fields',
    'administer paragraphs_library_item form display',
    'administer paragraphs_type labels',
    'administer pathauto',
    'administer permissions',
    'administer pfdp',
    'administer r4032login',
    'administer redirect settings',
    'administer redirects',
    'administer responsive images',
    'administer rest resources',
    'administer scheduled transitions',
    'administer seckit',
    'administer site configuration',
    'administer sitemap settings',
    'administer software updates',
    'administer stage_file_proxy settings',
    'administer taxonomy',
    'administer taxonomy_term display',
    'administer taxonomy_term fields',
    'administer taxonomy_term form display',
    'administer taxonomy_vocabulary labels',
    'administer themes',
    'administer url aliases',
    'administer user display',
    'administer user fields',
    'administer user form display',
    'administer users',
    'administer view_mode_page',
    'administer views',
    'administer workflows',
    'administer_mailsystem',
    'bulk delete aliases',
    'bulk update aliases',
    'bypass entityaccess userreference',
    'bypass node access',
    'bypass pfdp',
    'bypass pfdp for temporary files',
    'cancel account',
    'change own username',
    'clone action content',
    'clone advisory content',
    'clone alert content',
    'clone api_service_card content',
    'clone binder content',
    'clone campaign_landing content',
    'clone contact_information content',
    'clone curated_list content',
    'clone decision content',
    'clone decision_tree content',
    'clone decision_tree_branch content',
    'clone decision_tree_conclusion content',
    'clone error_page content',
    'clone event content',
    'clone executive_order content',
    'clone external_data_resource content',
    'clone fee content',
    'clone form_page content',
    'clone glossary content',
    'clone guide_page content',
    'clone how_to_page content',
    'clone info_details content',
    'clone interstitial content',
    'clone location content',
    'clone location_details content',
    'clone news content',
    'clone org_page content',
    'clone page content',
    'clone person content',
    'clone regulation content',
    'clone rules content',
    'clone service_page content',
    'clone sitewide_alert content',
    'clone stacked_layout content',
    'clone topic_page content',
    'clone utility_drawer content',
    'create action content',
    'create advisory content',
    'create alert content',
    'create api_service_card content',
    'create binder content',
    'create campaign_landing content',
    'create contact_information content',
    'create content translations',
    'create curated_list content',
    'create decision content',
    'create decision_tree content',
    'create decision_tree_branch content',
    'create decision_tree_conclusion content',
    'create document media',
    'create error_page content',
    'create event content',
    'create executive_order content',
    'create external_data_resource content',
    'create fee content',
    'create form_page content',
    'create glossary content',
    'create guide_page content',
    'create how_to_page content',
    'create info_details content',
    'create interstitial content',
    'create location content',
    'create location_details content',
    'create media',
    'create media_video media',
    'create news content',
    'create org_page content',
    'create page content',
    'create paragraph library item',
    'create person content',
    'create regulation content',
    'create rules content',
    'create service_page content',
    'create sitewide_alert content',
    'create stacked_layout content',
    'create terms in action_type',
    'create terms in adjustment_type',
    'create terms in advisory_publish_state',
    'create terms in advisory_type',
    'create terms in announcement_type',
    'create terms in billing_organizations',
    'create terms in binder_type',
    'create terms in collections',
    'create terms in content_type',
    'create terms in data_topic',
    'create terms in decision_participant_type',
    'create terms in decision_type',
    'create terms in document_category',
    'create terms in document_contacts',
    'create terms in document_creators',
    'create terms in document_other_type',
    'create terms in document_subjects',
    'create terms in document_tags',
    'create terms in event_type',
    'create terms in icons',
    'create terms in label',
    'create terms in language',
    'create terms in license',
    'create terms in location_activities',
    'create terms in location_icon',
    'create terms in location_icon_park',
    'create terms in organization_type',
    'create terms in rules_of_court_standing_order',
    'create terms in rules_of_court_type',
    'create terms in tags',
    'create terms in tx_data_resource_type',
    'create terms in tx_details_data_type',
    'create terms in tx_list_data_type',
    'create terms in type',
    'create terms in user_organization',
    'create topic_page content',
    'create url aliases',
    'create utility_drawer content',
    'delete action revisions',
    'delete advisory revisions',
    'delete alert revisions',
    'delete all revisions',
    'delete all taxonomy revisions',
    'delete any action content',
    'delete any advisory content',
    'delete any alert content',
    'delete any api_service_card content',
    'delete any binder content',
    'delete any campaign_landing content',
    'delete any contact_information content',
    'delete any curated_list content',
    'delete any decision content',
    'delete any decision_tree content',
    'delete any decision_tree_branch content',
    'delete any decision_tree_conclusion content',
    'delete any document media',
    'delete any document media revisions',
    'delete any error_page content',
    'delete any event content',
    'delete any executive_order content',
    'delete any external_data_resource content',
    'delete any fee content',
    'delete any file',
    'delete any form_page content',
    'delete any glossary content',
    'delete any guide_page content',
    'delete any how_to_page content',
    'delete any info_details content',
    'delete any interstitial content',
    'delete any location content',
    'delete any location_details content',
    'delete any media',
    'delete any media_video media',
    'delete any media_video media revisions',
    'delete any news content',
    'delete any org_page content',
    'delete any page content',
    'delete any person content',
    'delete any regulation content',
    'delete any rules content',
    'delete any service_page content',
    'delete any sitewide_alert content',
    'delete any stacked_layout content',
    'delete any topic_page content',
    'delete any utility_drawer content',
    'delete api_service_card revisions',
    'delete authmap',
    'delete binder revisions',
    'delete campaign_landing revisions',
    'delete conditional fields',
    'delete contact_information revisions',
    'delete content translations',
    'delete curated_list revisions',
    'delete decision revisions',
    'delete decision_tree revisions',
    'delete decision_tree_branch revisions',
    'delete decision_tree_conclusion revisions',
    'delete error_page revisions',
    'delete event revisions',
    'delete executive_order revisions',
    'delete external_data_resource revisions',
    'delete fee revisions',
    'delete file entities',
    'delete form_page revisions',
    'delete glossary revisions',
    'delete guide_page revisions',
    'delete how_to_page revisions',
    'delete info_details revisions',
    'delete interstitial revisions',
    'delete location revisions',
    'delete location_details revisions',
    'delete media',
    'delete news revisions',
    'delete org_page revisions',
    'delete orphan revisions',
    'delete own action content',
    'delete own advisory content',
    'delete own alert content',
    'delete own api_service_card content',
    'delete own binder content',
    'delete own campaign_landing content',
    'delete own contact_information content',
    'delete own curated_list content',
    'delete own decision content',
    'delete own decision_tree content',
    'delete own decision_tree_branch content',
    'delete own decision_tree_conclusion content',
    'delete own document media',
    'delete own error_page content',
    'delete own event content',
    'delete own executive_order content',
    'delete own external_data_resource content',
    'delete own fee content',
    'delete own files',
    'delete own form_page content',
    'delete own glossary content',
    'delete own guide_page content',
    'delete own how_to_page content',
    'delete own info_details content',
    'delete own interstitial content',
    'delete own location content',
    'delete own location_details content',
    'delete own media_video media',
    'delete own news content',
    'delete own org_page content',
    'delete own page content',
    'delete own person content',
    'delete own regulation content',
    'delete own rules content',
    'delete own service_page content',
    'delete own sitewide_alert content',
    'delete own stacked_layout content',
    'delete own topic_page content',
    'delete own utility_drawer content',
    'delete page revisions',
    'delete person revisions',
    'delete regulation revisions',
    'delete rules revisions',
    'delete service_page revisions',
    'delete sitewide_alert revisions',
    'delete stacked_layout revisions',
    'delete term revisions in action_type',
    'delete term revisions in adjustment_type',
    'delete term revisions in advisory_publish_state',
    'delete term revisions in advisory_type',
    'delete term revisions in announcement_type',
    'delete term revisions in billing_organizations',
    'delete term revisions in binder_type',
    'delete term revisions in collections',
    'delete term revisions in content_type',
    'delete term revisions in data_topic',
    'delete term revisions in decision_participant_type',
    'delete term revisions in decision_type',
    'delete term revisions in document_category',
    'delete term revisions in document_contacts',
    'delete term revisions in document_creators',
    'delete term revisions in document_other_type',
    'delete term revisions in document_subjects',
    'delete term revisions in document_tags',
    'delete term revisions in event_type',
    'delete term revisions in icons',
    'delete term revisions in label',
    'delete term revisions in language',
    'delete term revisions in license',
    'delete term revisions in location_activities',
    'delete term revisions in location_icon',
    'delete term revisions in location_icon_park',
    'delete term revisions in organization_type',
    'delete term revisions in rules_of_court_standing_order',
    'delete term revisions in rules_of_court_type',
    'delete term revisions in tags',
    'delete term revisions in tx_data_resource_type',
    'delete term revisions in tx_details_data_type',
    'delete term revisions in tx_list_data_type',
    'delete term revisions in type',
    'delete term revisions in user_organization',
    'delete terms in action_type',
    'delete terms in adjustment_type',
    'delete terms in advisory_publish_state',
    'delete terms in advisory_type',
    'delete terms in announcement_type',
    'delete terms in billing_organizations',
    'delete terms in binder_type',
    'delete terms in collections',
    'delete terms in content_type',
    'delete terms in data_topic',
    'delete terms in decision_participant_type',
    'delete terms in decision_type',
    'delete terms in document_category',
    'delete terms in document_contacts',
    'delete terms in document_creators',
    'delete terms in document_other_type',
    'delete terms in document_subjects',
    'delete terms in document_tags',
    'delete terms in event_type',
    'delete terms in icons',
    'delete terms in label',
    'delete terms in language',
    'delete terms in license',
    'delete terms in location_activities',
    'delete terms in location_icon',
    'delete terms in location_icon_park',
    'delete terms in organization_type',
    'delete terms in rules_of_court_standing_order',
    'delete terms in rules_of_court_type',
    'delete terms in tags',
    'delete terms in tx_data_resource_type',
    'delete terms in tx_details_data_type',
    'delete terms in tx_list_data_type',
    'delete terms in type',
    'delete terms in user_organization',
    'delete token',
    'delete topic_page revisions',
    'delete utility_drawer revisions',
    'disconnect openid connected accounts',
    'display manage tab',
    'download media',
    'dropzone upload files',
    'duplicate layout paragraphs components',
    'edit any action content',
    'edit any advisory content',
    'edit any alert content',
    'edit any api_service_card content',
    'edit any binder content',
    'edit any campaign_landing content',
    'edit any contact_information content',
    'edit any curated_list content',
    'edit any decision content',
    'edit any decision_tree content',
    'edit any decision_tree_branch content',
    'edit any decision_tree_conclusion content',
    'edit any document media',
    'edit any error_page content',
    'edit any event content',
    'edit any executive_order content',
    'edit any external_data_resource content',
    'edit any fee content',
    'edit any form_page content',
    'edit any glossary content',
    'edit any guide_page content',
    'edit any how_to_page content',
    'edit any info_details content',
    'edit any interstitial content',
    'edit any location content',
    'edit any location_details content',
    'edit any media_video media',
    'edit any news content',
    'edit any org_page content',
    'edit any page content',
    'edit any person content',
    'edit any regulation content',
    'edit any rules content',
    'edit any service_page content',
    'edit any sitewide_alert content',
    'edit any stacked_layout content',
    'edit any topic_page content',
    'edit any utility_drawer content',
    'edit behavior plugin settings',
    'edit conditional fields',
    'edit layout paragraphs plugin config',
    'edit own action content',
    'edit own advisory content',
    'edit own alert content',
    'edit own api_service_card content',
    'edit own binder content',
    'edit own campaign_landing content',
    'edit own contact_information content',
    'edit own curated_list content',
    'edit own decision content',
    'edit own decision_tree content',
    'edit own decision_tree_branch content',
    'edit own decision_tree_conclusion content',
    'edit own document media',
    'edit own error_page content',
    'edit own event content',
    'edit own executive_order content',
    'edit own external_data_resource content',
    'edit own fee content',
    'edit own form_page content',
    'edit own glossary content',
    'edit own guide_page content',
    'edit own how_to_page content',
    'edit own info_details content',
    'edit own interstitial content',
    'edit own location content',
    'edit own location_details content',
    'edit own media_video media',
    'edit own news content',
    'edit own org_page content',
    'edit own page content',
    'edit own person content',
    'edit own regulation content',
    'edit own rules content',
    'edit own service_page content',
    'edit own sitewide_alert content',
    'edit own stacked_layout content',
    'edit own topic_page content',
    'edit own utility_drawer content',
    'edit paragraph library item',
    'edit terms in action_type',
    'edit terms in adjustment_type',
    'edit terms in advisory_publish_state',
    'edit terms in advisory_type',
    'edit terms in announcement_type',
    'edit terms in billing_organizations',
    'edit terms in binder_type',
    'edit terms in collections',
    'edit terms in content_type',
    'edit terms in data_topic',
    'edit terms in decision_participant_type',
    'edit terms in decision_type',
    'edit terms in document_category',
    'edit terms in document_contacts',
    'edit terms in document_creators',
    'edit terms in document_other_type',
    'edit terms in document_subjects',
    'edit terms in document_tags',
    'edit terms in event_type',
    'edit terms in icons',
    'edit terms in label',
    'edit terms in language',
    'edit terms in license',
    'edit terms in location_activities',
    'edit terms in location_icon',
    'edit terms in location_icon_park',
    'edit terms in organization_type',
    'edit terms in rules_of_court_standing_order',
    'edit terms in rules_of_court_type',
    'edit terms in tags',
    'edit terms in tx_data_resource_type',
    'edit terms in tx_details_data_type',
    'edit terms in tx_list_data_type',
    'edit terms in type',
    'edit terms in user_organization',
    'execute entity:publish_action media',
    'execute entity:publish_action menu_link_content',
    'execute entity:publish_action node',
    'execute entity:publish_action paragraph',
    'execute entity:publish_action paragraphs_library_item',
    'execute entity:publish_action path_alias',
    'execute entity:publish_action taxonomy_term',
    'execute entity:save_action access_token',
    'execute entity:save_action file',
    'execute entity:save_action media',
    'execute entity:save_action menu_link_content',
    'execute entity:save_action node',
    'execute entity:save_action paragraphs_library_item',
    'execute entity:save_action taxonomy_term',
    'execute entity:save_action user',
    'execute entity:unpublish_action media',
    'execute entity:unpublish_action menu_link_content',
    'execute entity:unpublish_action node',
    'execute entity:unpublish_action paragraph',
    'execute entity:unpublish_action paragraphs_library_item',
    'execute entity:unpublish_action path_alias',
    'execute entity:unpublish_action taxonomy_term',
    'execute flag_delete_flagging flagging',
    'execute mass_content_moderation_restore_action all',
    'execute mass_hierarchy_change_parent all',
    'execute mass_media_publish media',
    'execute mass_media_restricted media',
    'execute mass_media_trash media',
    'execute mass_media_unpublish media',
    'execute mass_views_add_documents_collections media',
    'execute mass_views_change_collections node',
    'execute moderation_state_change crop',
    'execute moderation_state_change media',
    'execute moderation_state_change node',
    'execute moderation_state_change paragraphs_library_item',
    'execute moderation_state_change taxonomy_term',
    'execute node_assign_owner_action node',
    'execute node_make_sticky_action node',
    'execute node_make_unsticky_action node',
    'execute node_promote_action node',
    'execute node_unpromote_action node',
    'execute node_unpublish_by_keyword_action node',
    'execute user_add_role_action user',
    'execute user_block_user_action user',
    'execute user_remove_role_action user',
    'execute user_unblock_user_action user',
    'execute vbo_cancel_user_action user',
    'execute views_bulk_edit all',
    'execute views_bulk_operations_delete_entity all',
    'execute watch_content_flag node',
    'execute watch_content_unflag node',
    'export configuration',
    'flag watch_content',
    'ignore 404 requests',
    'import configuration',
    'link to any page',
    'manage editoria11y results',
    'manage own openid connect accounts',
    'mark as hidden in editoria11y',
    'mark as ok in editoria11y',
    'mass_flagging flag content',
    'mass_hierarchy - change parent on move children tab',
    'mass_hierarchy - change topic page parent',
    'mass_hierarchy - move items in the hierarchy',
    'never autoplay videos',
    'notify of path changes',
    'openid connect set own password',
    'perform batch updates entity usage',
    'purge akamai cache',
    'rabbit hole administer node',
    'rabbit hole administer taxonomy_term',
    'rabbit hole bypass node',
    'rabbit hole bypass taxonomy_term',
    'renew token',
    'reorder entity_hierarchy children',
    'reorder layout paragraphs components',
    'reschedule scheduled transitions media document',
    'reschedule scheduled transitions node action',
    'reschedule scheduled transitions node advisory',
    'reschedule scheduled transitions node alert',
    'reschedule scheduled transitions node binder',
    'reschedule scheduled transitions node campaign_landing',
    'reschedule scheduled transitions node contact_information',
    'reschedule scheduled transitions node curated_list',
    'reschedule scheduled transitions node decision',
    'reschedule scheduled transitions node decision_tree',
    'reschedule scheduled transitions node decision_tree_branch',
    'reschedule scheduled transitions node decision_tree_conclusion',
    'reschedule scheduled transitions node event',
    'reschedule scheduled transitions node executive_order',
    'reschedule scheduled transitions node external_data_resource',
    'reschedule scheduled transitions node fee',
    'reschedule scheduled transitions node form_page',
    'reschedule scheduled transitions node guide_page',
    'reschedule scheduled transitions node how_to_page',
    'reschedule scheduled transitions node info_details',
    'reschedule scheduled transitions node location',
    'reschedule scheduled transitions node location_details',
    'reschedule scheduled transitions node news',
    'reschedule scheduled transitions node org_page',
    'reschedule scheduled transitions node page',
    'reschedule scheduled transitions node person',
    'reschedule scheduled transitions node regulation',
    'reschedule scheduled transitions node rules',
    'reschedule scheduled transitions node service_page',
    'reschedule scheduled transitions node sitewide_alert',
    'reschedule scheduled transitions node stacked_layout',
    'reschedule scheduled transitions node topic_page',
    'restful get content_metadata_resource',
    'revert action revisions',
    'revert advisory revisions',
    'revert alert revisions',
    'revert all revisions',
    'revert all taxonomy revisions',
    'revert any document media revisions',
    'revert any media_video media revisions',
    'revert api_service_card revisions',
    'revert binder revisions',
    'revert campaign_landing revisions',
    'revert contact_information revisions',
    'revert curated_list revisions',
    'revert decision revisions',
    'revert decision_tree revisions',
    'revert decision_tree_branch revisions',
    'revert decision_tree_conclusion revisions',
    'revert error_page revisions',
    'revert event revisions',
    'revert executive_order revisions',
    'revert external_data_resource revisions',
    'revert fee revisions',
    'revert form_page revisions',
    'revert glossary revisions',
    'revert guide_page revisions',
    'revert how_to_page revisions',
    'revert info_details revisions',
    'revert interstitial revisions',
    'revert location revisions',
    'revert location_details revisions',
    'revert news revisions',
    'revert org_page revisions',
    'revert page revisions',
    'revert person revisions',
    'revert regulation revisions',
    'revert rules revisions',
    'revert service_page revisions',
    'revert sitewide_alert revisions',
    'revert stacked_layout revisions',
    'revert term revisions in action_type',
    'revert term revisions in adjustment_type',
    'revert term revisions in advisory_publish_state',
    'revert term revisions in advisory_type',
    'revert term revisions in announcement_type',
    'revert term revisions in billing_organizations',
    'revert term revisions in binder_type',
    'revert term revisions in collections',
    'revert term revisions in content_type',
    'revert term revisions in data_topic',
    'revert term revisions in decision_participant_type',
    'revert term revisions in decision_type',
    'revert term revisions in document_category',
    'revert term revisions in document_contacts',
    'revert term revisions in document_creators',
    'revert term revisions in document_other_type',
    'revert term revisions in document_subjects',
    'revert term revisions in document_tags',
    'revert term revisions in event_type',
    'revert term revisions in icons',
    'revert term revisions in label',
    'revert term revisions in language',
    'revert term revisions in license',
    'revert term revisions in location_activities',
    'revert term revisions in location_icon',
    'revert term revisions in location_icon_park',
    'revert term revisions in organization_type',
    'revert term revisions in rules_of_court_standing_order',
    'revert term revisions in rules_of_court_type',
    'revert term revisions in tags',
    'revert term revisions in tx_data_resource_type',
    'revert term revisions in tx_details_data_type',
    'revert term revisions in tx_list_data_type',
    'revert term revisions in type',
    'revert term revisions in user_organization',
    'revert topic_page revisions',
    'revert utility_drawer revisions',
    'run security checks',
    'select account cancellation method',
    'select which pages should suppress the header search',
    'set collection tags',
    'set info details page template',
    'synchronize configuration',
    'translate any entity',
    'translate api_service_card node',
    'translate editable entities',
    'unflag watch_content',
    'update any media',
    'update content translations',
    'update media',
    'use api_cards transition publish',
    'use api_cards transition unpublish',
    'use campaign_landing_page transition move_to_trash',
    'use campaign_landing_page transition needs_review',
    'use campaign_landing_page transition prepublished_draft',
    'use campaign_landing_page transition prepublished_needs_review',
    'use campaign_landing_page transition publish',
    'use campaign_landing_page transition to_draft',
    'use campaign_landing_page transition unpublish',
    'use change collections',
    'use content reports',
    'use editorial transition move_to_trash',
    'use editorial transition needs_review',
    'use editorial transition prepublished_draft',
    'use editorial transition prepublished_needs_review',
    'use editorial transition publish',
    'use editorial transition to_draft',
    'use editorial transition unpublish',
    'use key authentication',
    'use mass dashboard',
    'use mass dashboard tabs',
    'use media_states transition publish',
    'use media_states transition restriction_changes',
    'use media_states transition save_published',
    'use media_states transition save_unpublished',
    'use media_states transition send_to_trash',
    'use media_states transition to_draft',
    'use media_states transition unpublish',
    'use prototype design features',
    'use text format basic_html',
    'use text format campaign_custom_html',
    'use text format campaign_landing_basic',
    'use text format campaign_landing_restricted',
    'use text format collections_custom_html',
    'use text format full_html',
    'use text format mailchimp',
    'use text format restricted_html',
    'use text format rules_of_court_section',
    'use topic_page transition move_to_trash',
    'use topic_page transition needs_review',
    'use topic_page transition prepublished_draft',
    'use topic_page transition prepublished_needs_review',
    'use topic_page transition publish',
    'use topic_page transition to_draft',
    'use topic_page transition unpublish',
    'use views bulk edit',
    'view action revisions',
    'view advisory revisions',
    'view alert revisions',
    'view alerts block',
    'view all media revisions',
    'view all revisions',
    'view all scheduled transitions',
    'view all taxonomy revisions',
    'view analytics pages',
    'view any document media revisions',
    'view any media_video media revisions',
    'view any unpublished content',
    'view api_service_card revisions',
    'view authmap',
    'view binder revisions',
    'view campaign_landing revisions',
    'view conditional fields',
    'view contact_information revisions',
    'view curated_list revisions',
    'view current moderation states',
    'view decision revisions',
    'view decision_tree revisions',
    'view decision_tree_branch revisions',
    'view decision_tree_conclusion revisions',
    'view editoria11y checker',
    'view error_page revisions',
    'view event revisions',
    'view executive_order revisions',
    'view external_data_resource revisions',
    'view fee revisions',
    'view form_page revisions',
    'view glossary revisions',
    'view guide_page revisions',
    'view how_to_page revisions',
    'view info_details revisions',
    'view interstitial revisions',
    'view latest version',
    'view location revisions',
    'view location_details revisions',
    'view media',
    'view migration messages',
    'view news revisions',
    'view org_page revisions',
    'view own unpublished content',
    'view own unpublished media',
    'view page revisions',
    'view person revisions',
    'view regulation revisions',
    'view rules revisions',
    'view scheduled transitions media document',
    'view scheduled transitions node action',
    'view scheduled transitions node advisory',
    'view scheduled transitions node alert',
    'view scheduled transitions node binder',
    'view scheduled transitions node campaign_landing',
    'view scheduled transitions node contact_information',
    'view scheduled transitions node curated_list',
    'view scheduled transitions node decision',
    'view scheduled transitions node decision_tree',
    'view scheduled transitions node decision_tree_branch',
    'view scheduled transitions node decision_tree_conclusion',
    'view scheduled transitions node event',
    'view scheduled transitions node executive_order',
    'view scheduled transitions node external_data_resource',
    'view scheduled transitions node fee',
    'view scheduled transitions node form_page',
    'view scheduled transitions node guide_page',
    'view scheduled transitions node how_to_page',
    'view scheduled transitions node info_details',
    'view scheduled transitions node location',
    'view scheduled transitions node location_details',
    'view scheduled transitions node news',
    'view scheduled transitions node org_page',
    'view scheduled transitions node page',
    'view scheduled transitions node person',
    'view scheduled transitions node regulation',
    'view scheduled transitions node rules',
    'view scheduled transitions node service_page',
    'view scheduled transitions node sitewide_alert',
    'view scheduled transitions node stacked_layout',
    'view scheduled transitions node topic_page',
    'view service_page revisions',
    'view sitewide_alert revisions',
    'view stacked_layout revisions',
    'view term revisions in action_type',
    'view term revisions in adjustment_type',
    'view term revisions in advisory_publish_state',
    'view term revisions in advisory_type',
    'view term revisions in announcement_type',
    'view term revisions in billing_organizations',
    'view term revisions in binder_type',
    'view term revisions in collections',
    'view term revisions in content_type',
    'view term revisions in data_topic',
    'view term revisions in decision_participant_type',
    'view term revisions in decision_type',
    'view term revisions in document_category',
    'view term revisions in document_contacts',
    'view term revisions in document_creators',
    'view term revisions in document_other_type',
    'view term revisions in document_subjects',
    'view term revisions in document_tags',
    'view term revisions in event_type',
    'view term revisions in icons',
    'view term revisions in label',
    'view term revisions in language',
    'view term revisions in license',
    'view term revisions in location_activities',
    'view term revisions in location_icon',
    'view term revisions in location_icon_park',
    'view term revisions in organization_type',
    'view term revisions in rules_of_court_standing_order',
    'view term revisions in rules_of_court_type',
    'view term revisions in tags',
    'view term revisions in tx_data_resource_type',
    'view term revisions in tx_details_data_type',
    'view term revisions in tx_list_data_type',
    'view term revisions in type',
    'view term revisions in user_organization',
    'view the administration theme',
    'view topic_page revisions',
    'view unpublished paragraphs',
    'view update notifications',
    'view user email addresses',
    'view utility_drawer revisions',
    'view vocabulary labels',
  );
  expectedArguments(\Drupal\Core\Session\AccountInterface::hasPermission(), 0, argumentsSet('permissions'));
  expectedArguments(\Drupal\Core\Access\AccessResult::allowedIfHasPermission(), 1, argumentsSet('permissions'));
  expectedArguments(\Drupal\user\RoleInterface::allowedIfHasPermission(), 0, argumentsSet('permissions'));
  expectedArguments(\Drupal\user\RoleInterface::grantPermission(), 0, argumentsSet('permissions'));
  expectedArguments(\Drupal\user\RoleInterface::revokePermission(), 0, argumentsSet('permissions'));

}
