<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function ai_seo_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.ai_seo':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Analyze your page SEO and receive recommendations on how to improve it.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_contextual_links_view_alter().
 */
function ai_seo_contextual_links_view_alter(&$element, $items) {
  if (!\Drupal::currentUser()->hasPermission('view seo reports')) {
    return;
  }

  if (isset($element['#contextual_links']['node'])) {
    $id = $element['#contextual_links']['node']['route_parameters']['node'];
    if (!empty($id)) {
      $url_params = [
        'node' => $id,
      ];

      $url = Url::fromRoute('entity.node.seo_analyzer', $url_params);

      $element['#links']['ai_seo'] = [
        'title' => t('Analyze SEO'),
        'url'   => $url,
      ];
    }
  }
}

/**
 * Implements hook_entity_operation().
 */
function ai_seo_entity_operation(EntityInterface $entity) {
  $operations = [];
  if (!\Drupal::currentUser()->hasPermission('view seo reports')) {
    return $operations;
  }

  if (!empty($entity->getEntityTypeId()) && !empty($entity->id()) && $entity->getEntityTypeId() === 'node') {
    $url_params = [
      'node' => $entity->id(),
    ];

    $url_options = [
      'query' => [
        'destination' => \Drupal::request()->getRequestUri(),
      ],
    ];

    $url = Url::fromRoute('entity.node.seo_analyzer', $url_params, $url_options);

    $operations['ai_seo'] = [
      'title'  => t('Analyze SEO'),
      'url'    => $url,
      'weight' => 100,
    ];
  }
  return $operations;
}
