#!/usr/bin/env bash

## Description: Open Sequel Ace with "circle" database opened.
## Usage: massdbsa
## Example: "ddev massdbsa"
## OSTypes: darwin
## HostBinaryExists: "/Applications/Sequel Ace.app"

open mysql://circle:circle@mass.local:3206/circle -a '/Applications/Sequel Ace.app/Contents/MacOS/Sequel Ace'
