<?php

/**
 * @file
 * Mass Moderation Migration.
 */

use Drupal\migrate\Plugin\migrate\destination\EntityRevision as CoreEntityRevision;
use Drupal\mass_moderation_migration\Plugin\migrate\destination\EntityRevision;

/**
 * Placeholder.
 *
 * @param array $definitions
 *   Defsinately.
 */
function mass_moderation_migration_migrate_destination_info_alter(array &$definitions) {
  foreach ($definitions as &$definition) {
    if ($definition['class'] == CoreEntityRevision::class) {
      $definition['class'] = EntityRevision::class;
    }
  }
}
