version: 2
snapshot:
  widths:
    - 320
    - 1024
    - 1920
  minHeight: 480
  percyCSS: "
        /* Disable animations. */
      *, *::before, *::after {
        animation-duration: 0s !important;
        transition-duration: 0s !important;
      }

      /* Mask random homepage image. */
      body.is-front .ma__search-banner {
        background: none !important;
      }

      /* Hide the focus-visible border around the mobile menu */
      .ma__header__hamburger__menu-button {
        outline: none !important;
      }

      /* Hide the sticky toc */
      #sticky-toc {
        display: none !important;
      }

      /* Make sure sticky nav stays at the top */
      /* @todo it'd be better to add a class to this which disables to functionality */
      .ma__sticky-nav {
        top: auto !important;
        bottom: -15px !important;
        position: absolute !important;
        z-index: 80;
      }

      .ma__organization-navigation.stuck {
        position: static !important;
        top: auto !important;
        left: auto !important;
        width: auto !important;
        margin-top: -20px !important;
        z-index: auto !important;
      }

      .ma__org-page .pre-content {
        padding-top: 0 !important;
      }"
  enableJavaScript: false
  cliEnableJavaScript: true
  disableShadowDOM: false
discovery:
  request-headers:
    - mass-bypass-rate-limit: MASS_BYPASS_RATE_LIMIT
  cookies:
    - expirationDate: 1798790400
    - path: /
    - name: im-bypass
    - value: true
    - hostOnly: false
    - httpOnly: false
    - secure: false
    - session: false
    - sameSite: Lax
  allowedHostnames: []
  disallowedHostnames:
    - www.googletagmanager.com,
    - script.crazyegg.com,
    - www.google-analytics.com,
    - js-agent.newrelic.com,
    - translate.google.com,
    - foresee.com,
    - www.youtube.com,
    - bam.nr-data.net,
    - maps.googleapis.com,
    - 9p83os0fkf.execute-api.us-east-1.amazonaws.com/v1/waittime,
    - player.vimeo.com,
    - https://massgov.github.io/FWE/PondMaps/dfw-pond-maps-table.html,
  networkIdleTimeout: 100
  captureMockedServiceWorker: false
upload:
  files: "**/*.{png,jpg,jpeg}"
  ignore: ""
  stripExtensions: false
