version: '3.1'

services:
  backstop:
    image: "backstopjs/backstopjs:6.0.4"
    volumes:
      - ./backstop:/src
    shm_size: 1gb
    entrypoint: [backstop, --config=/src/backstop.js]
    environment:
      # Pass auth variables to container.
      LOWER_ENVIR_AUTH_USER:
      LOWER_ENVIR_AUTH_PASS:
