version: '3.7'

services:
  backstop:
    image: "backstopjs/backstopjs:6.1.0"
    # Add init to reap Chrome processes, as noted at
    # https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker
    init: true
    volumes:
      - ./backstop:/src
    shm_size: 1gb
    entrypoint: [backstop, --config=/src/backstop.js]
    environment:
      # Pass auth variables to container.
      LOWER_ENVIR_AUTH_USER:
      LOWER_ENVIR_AUTH_PASS:
