ai_content_advisor.report_type.*:
  type: config_entity
  label: 'AI Content Advisor Report Type'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    prompt:
      type: text
      label: 'AI Prompt'
    status:
      type: boolean
      label: 'Status'
    uuid:
      type: string
      label: 'UUID'
    _core:
      type: _core