<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\node\NodeInterface;
use Drupal\paragraphs\ParagraphInterface;

/**
 * Implements hook_entity_presave().
 */
function mass_redirect_normalizer_entity_presave(EntityInterface $entity) {
  if (!$entity instanceof NodeInterface && !$entity instanceof ParagraphInterface) {
    return;
  }

  if (!empty($_ENV['MASS_REDIRECT_NORMALIZER_WORKER'])) {
    return;
  }

  /** @var \Drupal\mass_redirect_normalizer\RedirectLinkQueueEnqueuer $enqueuer */
  $enqueuer = \Drupal::service('mass_redirect_normalizer.enqueuer');
  $enqueuer->enqueueEntity($entity, 'presave');
}
