<?php

/**
 * Implements hook_uninstall().
 */
function mass_content_api_uninstall() {
  $table_names = [
    'mass_content_api_descendants',
    'mass_content_api_relationships',
    'descendant_relations',
    'descendant_debug'
  ];
  $schema = \Drupal::database()->schema();
  foreach ($table_names as $table_name) {
    if ($schema->tableExists($table_name)) {
      $schema->dropTable($table_name);
    }
  }
}
