<?php

/**
 * @file
 * MA Dashboard module.
 */

use Drupal\Core\Menu\MenuTreeParameters;
use Drupal\Core\Url;

/**
 * Implements hook_toolbar().
 *
 * Adds a dashboard link to the admin toolbar.
 *
 * Adds an add new content and an add new documents button to the admin toolbar.
 */
function mass_dashboard_toolbar() {
  $items = [];

  $items['mass_dashboard'] = [
    '#type' => 'toolbar_item',
    // The tab appears in the black bar and toggles the "tray" menu.
    'tab' => [
      '#type' => 'link',
      '#title' => t('Content'),
      '#url' => Url::fromRoute('mass_dashboard.my_work'),
      '#options' => [
        'attributes' => [
          'title' => t('Mass.gov editorial dashboard'),
        ],
      ],
      '#attributes' => [
        'class' => ['toolbar-icon', 'toolbar-icon-mass-dashboard-tab'],
      ],
    ],
    // Pre_render adds tray items dynamically from the mass-dashboard menu.
    'tray' => [
      '#heading' => t('Editorial Dashboard'),
      'mass_dashboard_toolbar' => [
        '#pre_render' => [
          'mass_dashboard_toolbar_prerender_tray',
        ],
      ],
      '#type' => 'container',
      '#attributes' => [
        'class' => ['toolbar-menu-administration'],
      ],
    ],
    '#attached' => [
      'library' => [
        'mass_dashboard/mass_dashboard.toolbar',
      ],
    ],
  ];

  $items['add_content_link'] = [
    '#type' => 'toolbar_item',
    'tab' => [
      '#type' => 'link',
      '#title' => t('Add content'),
      '#url' => Url::fromRoute('node.add_page'),
      '#attributes' => [
        'class' => ['button', 'button--add-content'],
      ],
    ],
    '#wrapper_attributes' => [
      'class' => [
        'add-content-toolbar-tab',
      ],
    ],
  ];

  $items['add_document_link'] = [
    '#type' => 'toolbar_item',
    'tab' => [
      '#type' => 'link',
      '#title' => t('Add document'),
      '#url' => Url::fromRoute('entity.media.add_form', [
        'media_type' => 'document',
      ]),
      '#attributes' => [
        'class' => ['button', 'button--add-content'],
      ],
    ],
    '#wrapper_attributes' => [
      'class' => [
        'add-document-toolbar-tab',
      ],
    ],
  ];

  return $items;
}

/**
 * Implements hook_toolbar_alter().
 *
 * Removes the acquia connector notice unless user can do something about it.
 *
 * Adds permission to display the Manage tab in the toolbar.
 *
 * Adds a css class to the user toolbar tab, and changes username to just 'User.'
 */
function mass_dashboard_toolbar_alter(&$items) {
  if (isset($items['acquia_connector'])) {
    unset($items['acquia_connector']);
  }

  $user = \Drupal::currentUser();

  if (!$user->hasPermission('display manage tab')) {
    unset($items['administration']);
  }

  $items['user']['#wrapper_attributes']['class'][] = 'user-toolbar-tab';
  $items['user']['tab']['#title'] = t('Account');
}

/**
 * Render the MA Dashboard toolbar tray.
 *
 * Add the items in the mass-dashboard menu to the Dashboard tray.
 * Copied shamelessly from the Workbench module.
 *
 * @param array $element
 *   The tray render array.
 *
 * @return array
 *   The tray render array with the Mass Dashboard items added.
 *
 * @see toolbar_prerender_toolbar_administration_tray()
 * @see drupal_render()
 */
function mass_dashboard_toolbar_prerender_tray(array $element) {
  $menu_tree = \Drupal::service('toolbar.menu_tree');

  $parameters = new MenuTreeParameters();
  $parameters->setMinDepth(1)->setMaxDepth(1);

  $tree = $menu_tree->load('mass-dashboard', $parameters);

  $manipulators = [
    ['callable' => 'menu.default_tree_manipulators:checkAccess'],
    ['callable' => 'menu.default_tree_manipulators:generateIndexAndSort'],
    ['callable' => 'toolbar_menu_navigation_links'],
  ];

  $tree = $menu_tree->transform($tree, $manipulators);

  $element['administration_menu'] = $menu_tree->build($tree);
  return $element;
}

/**
 * Implements hook_theme().
 */
function mass_dashboard_theme() {
  return [
    'mass_dashboard_message_tabs' => [
      'variables' => [
        'messages' => NULL,
        'tabs' => NULL,
      ],
    ],
    'mass_dashboard_tabs' => [
      'variables' => [
        'primary' => NULL,
        'secondary' => NULL,
      ],
    ],
  ];
}
