<?php

/**
 * @file
 * Contains mass_site_map.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function mass_site_map_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  // Add a description to the Simple Sitemap fieldset on the admin form.
  if (!empty($form['simple_sitemap']) && empty($form['simple_sitemap']['description'])) {
    $form['simple_sitemap']['description'] = [
      '#prefix' => '<div class="description">',
      '#suffix' => '</div>',
      '#markup' => t('Leave these settings alone unless you are advised by the Digital Services team to change them.'),
      '#weight' => -10,
    ];
  }
}

/**
 * Implements hook_simple_sitemap_sitemap_generators_alter().
 */
function mass_site_map_simple_sitemap_sitemap_generators_alter(array &$sitemap_generators) {
  // Remove the default generator.
  $sitemap_generators['default']['class'] = 'Drupal\mass_site_map\Plugin\simple_sitemap\SitemapGenerator\MassSitemapGenerator';
}


/**
 * Implements hook_simple_sitemap_url_generators_alter().
 */
function mass_site_map_simple_sitemap_url_generators_alter(array &$url_generators) {
  $url_generators['entity']['class'] = $url_generators['mass_entity']['class'];
}
