#!/usr/bin/env bash
####
#
# filescan-deploy
#
# This shell script encapsulates the commands needed to deploy our file scanning configuration.
# The only thing you need to run this script are AWS credentials, which must be made available
# outside of this script, usually by executing `aws-vault`.
#
# Example usage:
#    aws-vault exec massgov -- ./scripts/filescan-deploy
#
###

set -e

TFVERSION="v0.12.3"

AUTO_APPROVE=""
if [[ "$2" = "--auto-approve" ]] ; then
  AUTO_APPROVE="-auto-approve"
fi

# Run pre-apply checks to be sure we have all the things we need.
which chamber > /dev/null 2>&1 || {
  echo "Chamber binary not found. Please install Chamber: https://github.com/segmentio/chamber"; exit 1;
}
which terraform > /dev/null 2>&1 || {
  echo "Terraform not found. Please install Terraform $TFVERSION: https://www.terraform.io/downloads.html"; exit 1;
}
terraform --version | grep -q "$TFVERSION" || {
  echo "Terraform was found, but is not the right version. Please use Terraform $TFVERSION"; exit 1;
}
