#!/usr/bin/env bash

# This is a convenience script for linting files & running behat tests.

echo -e "\n"
# cd into project root
echo -e "ℹ️  Changing directory to '/var/www/mass.local'  🚀  🚀  🚀"
cd /var/www/mass.local

# check drupal coding standards with php code sniffer
echo -e "\n🔍  Validate .json and check if it is in sync with the .lock file"
composer validate

# check drupal coding standards with php code sniffer
echo -e "\n🔍  Running PHP Code Sniffer"
phpcs -n

# lint javascript
echo -e "\n🔍  Running ESLint"
# use --debug for verbose output
yarn run eslint --ignore-path 'docroot/.eslintignore' 'docroot/modules/custom/**/*.js' 'docroot/themes/custom/**/*.js'

# phpunit
echo -e "\n🔍  Running PHPUnit"
phpunit docroot/modules/custom

echo -e "\n🔍  Running Behat tests 🐝  🐝  🐝"
behat --strict
