#!/usr/bin/env bash

set -eo pipefail

SHA1=597bc96a83b5a71ce1d7fa1304c0c345969191c2
git diff-tree \
            -r \
            -z \
            --name-only \
            --no-commit-id \
            HEAD $SHA1 -- docroot/modules/custom | xargs -0 vendor/bin/phpcs --standard=phpcs.strict_types.xml
