#!/usr/bin/env bash

set -eo pipefail

SHA1=( $(curl -s -H "Authorization: token ${GITHUB_MASSGOV_BOT_TOKEN}" $(echo https://api.github.com/repos/${CIRCLE_PULL_REQUEST:19} | sed "s/\/pull\//\/pulls\//") | jq ".base.sha" | tr -d "\042" ) )
git diff-tree \
            -r \
            -z \
            --name-only \
            --no-commit-id \
            HEAD "${SHA1[@]}" -- docroot/modules/custom | xargs --no-run-if-empty -0 vendor/bin/phpcs --standard=phpcs.strict_types.xml
