#!/usr/bin/env bash

# exit when any command fails
set -e

GITHUB_MASSGOV_BOT_TOKEN="9208e25c2abe9af23683ebcd053a5385a98ec5b7"
TAG="LASTOneD"

# Use AWK ORS - The output record separator.
# https://linux.die.net/man/1/awk
cat ./scripts/changelog-body.txt |  awk '{print}' ORS='\\n' > /tmp/changelog-body.txt

# Create post data
generate_post_data()
{
  cat <<EOF
  {
  "tag_name": "${TAG}",
  "target_commitish": "master",
  "name": "${TAG}",
  "body": "$(cat /tmp/changelog-body.txt)",
  "draft": false,
  "prerelease": false
  }
EOF
}

# DATA=$(generate_post_data)

# # Create a release on GitHub for the tag that was just created.
curl -X POST --data "$(generate_post_data)" -u massgov-bot:"${GITHUB_MASSGOV_BOT_TOKEN}" -H "Content-Type:application/json"  https://api.github.com/repos/yriahi/riahi-infrastructure/releases
