#!/usr/bin/env bash
if [[ "$1" = "on" ]] ; then
  echo "Enabling xdebug";
  # Uncomment out the extension include.
  sed -i 's/^; \(zend_extension=.*xdebug\)$/\1/' $PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini
  /etc/init.d/apache2 reload
elif [[ "$1" = "off" ]] ; then
  echo "Disabling xdebug";
  # Comment out the extension include.
  sed -i 's/^\(zend_extension=.*xdebug\)$/; \1/' $PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini
  /etc/init.d/apache2 reload
fi
