#!/bin/bash

## Description: Run nightcrawler
## Usage: nightcrawler [flags] [args]
## Example: ddev nightcrawler -- --target=local --samples=50

node_modules/.bin/nightcrawler crawl --config=.circleci/nightcrawler/nightcrawler $@
