#!/bin/bash

## Description: Run nightcrawler
## Usage: nightcrawler [flags] [args]
## Example: ddev nightcrawler crawl --target=local --samples=50

node_modules/.bin/nightcrawler --config=.circleci/nightcrawler/nightcrawler $@
