mass_analytics.settings:
  type: config_object
  label: 'Mass Analytics settings'
  mapping:
    dashboard_embed_url:
      type: string
      label: 'URL'
    looker_studio_url:
      type: string
      label: 'Legacy URL'
