<?php

/**
 * @file
 * Contains mass_hierarchy.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\mass_hierarchy\Form\HierarchyChildrenForm;

/**
 * Implements hook_help().
 */
function mass_hierarchy_help($route_name, RouteMatchInterface $route_match) {
  $output = '';
  switch ($route_name) {
    case 'view.change_parents.page_1':
      $output .= '<p><strong>' . t('NOTE: Moving children in bulk is an experimental feature and is currently slow.') . '</strong>';
      $output .= t(' It may take one minute or more before you see an indication that your move starts. In testing, we have seen it take two minutes to change the parent on 25 children. We will evaluate this after release to production to assess performance and to see if we can speed the process.') . '</p>';
      break;

    default:
  }

  // Looking for entity.[bundle].entity_hierarchy_reorder.
  if (
    strpos($route_name, 'entity.') === 0 &&
    strpos(strrev($route_name), strrev('.entity_hierarchy_reorder')) === 0
  ) {
    $sentences = [
      '<b>NOTE:</b> This new feature is experimental. It shows children and descendents of the current page that are published. You can expand children that have children of their own, and you can drag pages to be children of a new parent. You can drag pages left and right to move them up or down in the hierarchy. Please save often because if you navigate away from this tab, any changes will be lost. Report any issues with ServiceNow.',
      'The order of the pages in the hierarchy doesn’t matter and isn’t changed if you move them just up or down - it is only the parent/child relationships that are saved.',
      'Moving a page to a new parent does NOT add a link on the parent to the child. If you need that, you will have to add it manually.',
    ];
    $output = '<p>' . implode('</p><p>', $sentences) . '</p>';
  }

  return $output;
}

/**
 * Builds what bundles are supported to parents of the available bundles.
 */
function mass_hierarchy_get_parent_bundle_info() {
  /** @var Drupal\Core\Entity\EntityTypeBundleInfo */
  $entity_type_bundle_info_service = \Drupal::service('entity_type.bundle.info');
  $bundles = $entity_type_bundle_info_service->getBundleInfo('node');

  /** @var \Drupal\Core\Entity\EntityFieldManager */
  $entity_field_manager_service = \Drupal::getContainer()->get('entity_field.manager');

  foreach ($bundles as $bundle_name => $bundle_info) {
    $field_definitions = $entity_field_manager_service->getFieldDefinitions('node', $bundle_name);
    if (!isset($field_definitions['field_primary_parent'])) {
      continue;
    }
    $info[$bundle_name] = $field_definitions['field_primary_parent']->getSetting('handler_settings')['target_bundles'];
  }
  return $info;
}

/**
 * Implements @see hook_entity_type_build().
 *
 * @see entity_hierarchy_entity_type_build
 */
function mass_hierarchy_entity_type_build(array &$entity_types) {
  /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */
  foreach ($entity_types as $entity_type_id => $entity_type) {
    $entity_types[$entity_type_id]
      ->setFormClass('entity_hierarchy_reorder', HierarchyChildrenForm::class);
  }
}

/**
 * Implements hook_views_pre_view().
 */
function mass_hierarchy_views_pre_view($view) {
  /** @var \Drupal\views\Entity\View $view */
  if ($view->id() != 'change_parents') {
    return;
  }

  $filters = $view->display_handler->getOption('filters');

  if (!isset($filters['type_1'])) {
    return;
  }

  if (!\Drupal::currentUser()->hasPermission('create topic_page content')) {
    return;
  }

  // Include topic pages on the view by removing the filter.
  unset($filters['type_1']);
  $view->display_handler->overrideOption('filters', $filters);
}
