<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\mass_content_moderation\MassModeration;
use Drupal\mass_redirects\Form\MoveRedirectsForm;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function mass_redirects_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  foreach (array_keys($form['actions']) as $action) {
    if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
      $form['actions'][$action]['#submit'][] = 'mass_redirects_node_form_submit';
    }
  }
  return $form;
}

/**
 * Upon saving a trashed node, give link to Move Redirects form.
 *
 * We can't easily use hook_node_update since the node URL changes to ---unpublished in pathauto_alias_alter hook.
 * We don't use hook_entity_update since that was spamming during bulk update. See https://massgov.atlassian.net/browse/DP-26408
 */
function mass_redirects_node_form_submit($form, FormStateInterface $form_state) {
  /** @var \Drupal\mass_content\Entity\Bundle\node\NodeBundle $entity */
  $entity = $form_state->getFormObject()->getEntity();
  if (PHP_SAPI !== 'cli' && $entity->getModerationState()->getString() == MassModeration::TRASH) {
    $id = $entity->id();
    $message = 'You may be able to <a href="@redirect-page">Redirect this trashed page</a> so that visitors will not get a <em>Page not Found</em> error.';
    Drupal::messenger()->addWarning(t($message, ['@redirect-page' => $entity->toUrl('redirects')->toString()]));
  }
}

/**
 * Implements hook_entity_operation().
 */
function mass_redirects_entity_operation(EntityInterface $entity): array {
  if ($entity->getEntityTypeId() == 'node') {
    $url = $entity->toUrl('redirects');
    if ($url->access()) {
      $operations['redirects'] = [
        'title' => \t('Redirects'),
        'url' => $url,
        'weight' => 50,
      ];
    }
  }

  return $operations ?? [];
}

/**
 * Implements hook_entity_type_alter().
 */
function mass_redirects_entity_type_alter(array &$entity_types) {
  /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */
  $handlers = $entity_types['node']->getHandlerClasses();
  $handlers['form']['move-redirects'] = MoveRedirectsForm::class;
  $entity_types['node']->setHandlerClass('form', $handlers['form']);

  $redirects_path = $entity_types['node']->getLinkTemplate('canonical') . '/redirects';
  $entity_types['node']->setLinkTemplate('redirects', $redirects_path);
}
