services:
  # This is the service name used when running ddev commands accepting the
  # --service flag.
  memcached:
    # This is the name of the container. It is recommended to follow the same
    # name convention used in the main docker-compose.yml file.
    container_name: ddev-${DDEV_SITENAME}-memcached
    image: memcached:1.5
    restart: "no"
    # memcached is available at this port inside the container.
    expose:
      - 11211
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}

    # Arguments passed to the memcached binary.
    command: ["-m", "128"]

    volumes:
      - ".:/mnt/ddev_config"
  web:
    links:
      - memcached:memcached
