# The following database service uses a `percona-server:5.6.40` image where mysql initialization done by
# a custom `docker-entrypoint.sh` script. You can find that script and the `Dockerfile` in `.circleci/mysql-rebuild/`.
# See https://medium.com/massgovdigital/dev-env-5d35b97f3473#cba3 for more info.
# Further, the image is super sanitized (no unpublished content, old revisions, user data, etc.).
services:
  dbmass:
    container_name: ddev-${DDEV_SITENAME}-dbmass
    image: ${MASS_DB_IMAGE-massgov/mysql-sanitized:super}
    ports:
      - 3206:3306
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      MYSQL_USER: circle
      MYSQL_PASSWORD: circle
      MYSQL_DATABASE: circle
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    command: --max_allowed_packet=32M --innodb_flush_method=O_DIRECT --tmp_table_size=16M --query_cache_size=16M --innodb-flush-log-at-trx-commit=2  --innodb_buffer_pool_size=500M --innodb_log_buffer_size=64M --skip-innodb_doublewrite --innodb_log_file_size=64M
    volumes:
      - dbmass:/var/lib/mysql
  web:
    links:
      - dbmass:dbmass
volumes:
  dbmass:
