version: '3.6'

services:
  # This is the service name used when running ddev commands accepting the
  # --service flag.
  portainer:
    # This is the name of the container. It is recommended to follow the same
    # name convention used in the main docker-compose.yml file.
    container_name: ddev-${DDEV_SITENAME}-portainer
    image: portainer/portainer
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=8089:9000
    expose:
      - 9000
    # These labels ensure this service is discoverable by ddev.
    external_links:
      - "ddev-router:${DDEV_HOSTNAME}"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

